//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApprovalEntriesServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries", ConfigurationName="ApprovalEntriesServiceReference.DEFT_ApprovalEntries_Port")]
    public interface DEFT_ApprovalEntries_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_approvalentries:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ApprovalEntriesServiceReference.ReadByRecId_Result> ReadByRecIdAsync(ApprovalEntriesServiceReference.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_approvalentries:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ApprovalEntriesServiceReference.ReadMultiple_Result> ReadMultipleAsync(ApprovalEntriesServiceReference.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_approvalentries:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ApprovalEntriesServiceReference.IsUpdated_Result> IsUpdatedAsync(ApprovalEntriesServiceReference.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_approvalentries:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ApprovalEntriesServiceReference.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(ApprovalEntriesServiceReference.GetRecIdFromKey request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries")]
    public partial class DEFT_ApprovalEntries
    {
        
        private string keyField;
        
        private int table_IDField;
        
        private bool table_IDFieldSpecified;
        
        private Limit_Type limit_TypeField;
        
        private bool limit_TypeFieldSpecified;
        
        private Approval_Type approval_TypeField;
        
        private bool approval_TypeFieldSpecified;
        
        private Document_Type document_TypeField;
        
        private bool document_TypeFieldSpecified;
        
        private string document_NoField;
        
        private string recordIDTextField;
        
        private string detailsField;
        
        private int sequence_NoField;
        
        private bool sequence_NoFieldSpecified;
        
        private Status statusField;
        
        private bool statusFieldSpecified;
        
        private string sender_IDField;
        
        private string salespers_Purch_CodeField;
        
        private string approver_IDField;
        
        private string currency_CodeField;
        
        private decimal amount_LCYField;
        
        private bool amount_LCYFieldSpecified;
        
        private decimal daysField;
        
        private bool daysFieldSpecified;
        
        private System.DateTime start_DateField;
        
        private bool start_DateFieldSpecified;
        
        private System.DateTime end_DateField;
        
        private bool end_DateFieldSpecified;
        
        private decimal available_Credit_Limit_LCYField;
        
        private bool available_Credit_Limit_LCYFieldSpecified;
        
        private System.DateTime date_Time_Sent_for_ApprovalField;
        
        private bool date_Time_Sent_for_ApprovalFieldSpecified;
        
        private System.DateTime last_Date_Time_ModifiedField;
        
        private bool last_Date_Time_ModifiedFieldSpecified;
        
        private string last_Modified_By_User_IDField;
        
        private bool commentField;
        
        private bool commentFieldSpecified;
        
        private System.DateTime due_DateField;
        
        private bool due_DateFieldSpecified;
        
        private string descriptionField;
        
        private string staff_NoField;
        
        private string vendor_NoField;
        
        private string approver_Staff_NoField;
        
        private System.DateTime payroll_period_start_DateField;
        
        private bool payroll_period_start_DateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Table_ID
        {
            get
            {
                return this.table_IDField;
            }
            set
            {
                this.table_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Table_IDSpecified
        {
            get
            {
                return this.table_IDFieldSpecified;
            }
            set
            {
                this.table_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Limit_Type Limit_Type
        {
            get
            {
                return this.limit_TypeField;
            }
            set
            {
                this.limit_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Limit_TypeSpecified
        {
            get
            {
                return this.limit_TypeFieldSpecified;
            }
            set
            {
                this.limit_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Approval_Type Approval_Type
        {
            get
            {
                return this.approval_TypeField;
            }
            set
            {
                this.approval_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Approval_TypeSpecified
        {
            get
            {
                return this.approval_TypeFieldSpecified;
            }
            set
            {
                this.approval_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Document_Type Document_Type
        {
            get
            {
                return this.document_TypeField;
            }
            set
            {
                this.document_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Document_TypeSpecified
        {
            get
            {
                return this.document_TypeFieldSpecified;
            }
            set
            {
                this.document_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Document_No
        {
            get
            {
                return this.document_NoField;
            }
            set
            {
                this.document_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string RecordIDText
        {
            get
            {
                return this.recordIDTextField;
            }
            set
            {
                this.recordIDTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Sequence_No
        {
            get
            {
                return this.sequence_NoField;
            }
            set
            {
                this.sequence_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Sequence_NoSpecified
        {
            get
            {
                return this.sequence_NoFieldSpecified;
            }
            set
            {
                this.sequence_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Sender_ID
        {
            get
            {
                return this.sender_IDField;
            }
            set
            {
                this.sender_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Salespers_Purch_Code
        {
            get
            {
                return this.salespers_Purch_CodeField;
            }
            set
            {
                this.salespers_Purch_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Approver_ID
        {
            get
            {
                return this.approver_IDField;
            }
            set
            {
                this.approver_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Currency_Code
        {
            get
            {
                return this.currency_CodeField;
            }
            set
            {
                this.currency_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public decimal Amount_LCY
        {
            get
            {
                return this.amount_LCYField;
            }
            set
            {
                this.amount_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Amount_LCYSpecified
        {
            get
            {
                return this.amount_LCYFieldSpecified;
            }
            set
            {
                this.amount_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public decimal Days
        {
            get
            {
                return this.daysField;
            }
            set
            {
                this.daysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DaysSpecified
        {
            get
            {
                return this.daysFieldSpecified;
            }
            set
            {
                this.daysFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=16)]
        public System.DateTime Start_Date
        {
            get
            {
                return this.start_DateField;
            }
            set
            {
                this.start_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Start_DateSpecified
        {
            get
            {
                return this.start_DateFieldSpecified;
            }
            set
            {
                this.start_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=17)]
        public System.DateTime End_Date
        {
            get
            {
                return this.end_DateField;
            }
            set
            {
                this.end_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool End_DateSpecified
        {
            get
            {
                return this.end_DateFieldSpecified;
            }
            set
            {
                this.end_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public decimal Available_Credit_Limit_LCY
        {
            get
            {
                return this.available_Credit_Limit_LCYField;
            }
            set
            {
                this.available_Credit_Limit_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Available_Credit_Limit_LCYSpecified
        {
            get
            {
                return this.available_Credit_Limit_LCYFieldSpecified;
            }
            set
            {
                this.available_Credit_Limit_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public System.DateTime Date_Time_Sent_for_Approval
        {
            get
            {
                return this.date_Time_Sent_for_ApprovalField;
            }
            set
            {
                this.date_Time_Sent_for_ApprovalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Date_Time_Sent_for_ApprovalSpecified
        {
            get
            {
                return this.date_Time_Sent_for_ApprovalFieldSpecified;
            }
            set
            {
                this.date_Time_Sent_for_ApprovalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public System.DateTime Last_Date_Time_Modified
        {
            get
            {
                return this.last_Date_Time_ModifiedField;
            }
            set
            {
                this.last_Date_Time_ModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Date_Time_ModifiedSpecified
        {
            get
            {
                return this.last_Date_Time_ModifiedFieldSpecified;
            }
            set
            {
                this.last_Date_Time_ModifiedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Last_Modified_By_User_ID
        {
            get
            {
                return this.last_Modified_By_User_IDField;
            }
            set
            {
                this.last_Modified_By_User_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public bool Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CommentSpecified
        {
            get
            {
                return this.commentFieldSpecified;
            }
            set
            {
                this.commentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=23)]
        public System.DateTime Due_Date
        {
            get
            {
                return this.due_DateField;
            }
            set
            {
                this.due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Due_DateSpecified
        {
            get
            {
                return this.due_DateFieldSpecified;
            }
            set
            {
                this.due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Staff_No
        {
            get
            {
                return this.staff_NoField;
            }
            set
            {
                this.staff_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Vendor_No
        {
            get
            {
                return this.vendor_NoField;
            }
            set
            {
                this.vendor_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Approver_Staff_No
        {
            get
            {
                return this.approver_Staff_NoField;
            }
            set
            {
                this.approver_Staff_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=28)]
        public System.DateTime Payroll_period_start_Date
        {
            get
            {
                return this.payroll_period_start_DateField;
            }
            set
            {
                this.payroll_period_start_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Payroll_period_start_DateSpecified
        {
            get
            {
                return this.payroll_period_start_DateFieldSpecified;
            }
            set
            {
                this.payroll_period_start_DateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries")]
    public enum Limit_Type
    {
        
        /// <remarks/>
        Approval_Limits,
        
        /// <remarks/>
        Credit_Limits,
        
        /// <remarks/>
        Request_Limits,
        
        /// <remarks/>
        No_Limits,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries")]
    public enum Approval_Type
    {
        
        /// <remarks/>
        Workflow_User_Group,
        
        /// <remarks/>
        Sales_Pers_Purchaser,
        
        /// <remarks/>
        Approver,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries")]
    public enum Document_Type
    {
        
        /// <remarks/>
        Quote,
        
        /// <remarks/>
        Order,
        
        /// <remarks/>
        Invoice,
        
        /// <remarks/>
        Credit_Memo,
        
        /// <remarks/>
        Blanket_Order,
        
        /// <remarks/>
        Return_Order,
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Payment_Voucher,
        
        /// <remarks/>
        Imprest,
        
        /// <remarks/>
        Imprest_Surrender,
        
        /// <remarks/>
        Petty_Cash,
        
        /// <remarks/>
        Petty_Cash_Surrender,
        
        /// <remarks/>
        Store_Requisitions,
        
        /// <remarks/>
        Purchase_Requisitions,
        
        /// <remarks/>
        Staff_Claim,
        
        /// <remarks/>
        Bank_Transfer,
        
        /// <remarks/>
        Staff_Advance,
        
        /// <remarks/>
        Quotation,
        
        /// <remarks/>
        QuoteEvaluation,
        
        /// <remarks/>
        LeaveAdjustment,
        
        /// <remarks/>
        TrainingRequest,
        
        /// <remarks/>
        LeaveApplication,
        
        /// <remarks/>
        Travel_Requests,
        
        /// <remarks/>
        Recruitment,
        
        /// <remarks/>
        Employee_Transfer,
        
        /// <remarks/>
        Employee_Appraisal,
        
        /// <remarks/>
        Leave_Recall,
        
        /// <remarks/>
        Maintenance_Registration,
        
        /// <remarks/>
        Payroll_Change,
        
        /// <remarks/>
        Payroll_Request,
        
        /// <remarks/>
        Payroll_Loan_Application,
        
        /// <remarks/>
        Employee_Acting,
        
        /// <remarks/>
        Employee_Promotion,
        
        /// <remarks/>
        Budget,
        
        /// <remarks/>
        Proposed_Budget,
        
        /// <remarks/>
        Bank_Reconciliation,
        
        /// <remarks/>
        Audit,
        
        /// <remarks/>
        Risk,
        
        /// <remarks/>
        Audit_WorkPlan,
        
        /// <remarks/>
        Audit_Record_Requisition,
        
        /// <remarks/>
        Audit_Plan,
        
        /// <remarks/>
        Work_Paper,
        
        /// <remarks/>
        Audit_Report,
        
        /// <remarks/>
        Risk_Survey,
        
        /// <remarks/>
        Audit_Program,
        
        /// <remarks/>
        FA_Disposal,
        
        /// <remarks/>
        PML_Registration,
        
        /// <remarks/>
        Loan_Application,
        
        /// <remarks/>
        Loan_Disbursement,
        
        /// <remarks/>
        Loan_Interest,
        
        /// <remarks/>
        Tender_Evaluation,
        
        /// <remarks/>
        Supplier_Evaluation,
        
        /// <remarks/>
        Staff_Payroll_Approval,
        
        /// <remarks/>
        Board_Payroll_Approval,
        
        /// <remarks/>
        Investment,
        
        /// <remarks/>
        Funding,
        
        /// <remarks/>
        Repair,
        
        /// <remarks/>
        PML_Change_Request,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries")]
    public enum Status
    {
        
        /// <remarks/>
        Created,
        
        /// <remarks/>
        Open,
        
        /// <remarks/>
        Canceled,
        
        /// <remarks/>
        Rejected,
        
        /// <remarks/>
        Approved,
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Pending_Approval,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries")]
    public partial class DEFT_ApprovalEntries_Filter
    {
        
        private DEFT_ApprovalEntries_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DEFT_ApprovalEntries_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries")]
    public enum DEFT_ApprovalEntries_Fields
    {
        
        /// <remarks/>
        Overdue,
        
        /// <remarks/>
        Table_ID,
        
        /// <remarks/>
        Limit_Type,
        
        /// <remarks/>
        Approval_Type,
        
        /// <remarks/>
        Document_Type,
        
        /// <remarks/>
        Document_No,
        
        /// <remarks/>
        RecordIDText,
        
        /// <remarks/>
        Details,
        
        /// <remarks/>
        Sequence_No,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        Sender_ID,
        
        /// <remarks/>
        Salespers_Purch_Code,
        
        /// <remarks/>
        Approver_ID,
        
        /// <remarks/>
        Currency_Code,
        
        /// <remarks/>
        Amount_LCY,
        
        /// <remarks/>
        Days,
        
        /// <remarks/>
        Start_Date,
        
        /// <remarks/>
        End_Date,
        
        /// <remarks/>
        Available_Credit_Limit_LCY,
        
        /// <remarks/>
        Date_Time_Sent_for_Approval,
        
        /// <remarks/>
        Last_Date_Time_Modified,
        
        /// <remarks/>
        Last_Modified_By_User_ID,
        
        /// <remarks/>
        Comment,
        
        /// <remarks/>
        Due_Date,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Staff_No,
        
        /// <remarks/>
        Vendor_No,
        
        /// <remarks/>
        Approver_Staff_No,
        
        /// <remarks/>
        Payroll_period_start_Date,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries", Order=0)]
        public ApprovalEntriesServiceReference.DEFT_ApprovalEntries DEFT_ApprovalEntries;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(ApprovalEntriesServiceReference.DEFT_ApprovalEntries DEFT_ApprovalEntries)
        {
            this.DEFT_ApprovalEntries = DEFT_ApprovalEntries;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public ApprovalEntriesServiceReference.DEFT_ApprovalEntries_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(ApprovalEntriesServiceReference.DEFT_ApprovalEntries_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ApprovalEntriesServiceReference.DEFT_ApprovalEntries[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(ApprovalEntriesServiceReference.DEFT_ApprovalEntries[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/deft_approvalentries", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface DEFT_ApprovalEntries_PortChannel : ApprovalEntriesServiceReference.DEFT_ApprovalEntries_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class DEFT_ApprovalEntries_PortClient : System.ServiceModel.ClientBase<ApprovalEntriesServiceReference.DEFT_ApprovalEntries_Port>, ApprovalEntriesServiceReference.DEFT_ApprovalEntries_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DEFT_ApprovalEntries_PortClient() : 
                base(DEFT_ApprovalEntries_PortClient.GetDefaultBinding(), DEFT_ApprovalEntries_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DEFT_ApprovalEntries_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DEFT_ApprovalEntries_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(DEFT_ApprovalEntries_PortClient.GetBindingForEndpoint(endpointConfiguration), DEFT_ApprovalEntries_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DEFT_ApprovalEntries_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DEFT_ApprovalEntries_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DEFT_ApprovalEntries_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DEFT_ApprovalEntries_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DEFT_ApprovalEntries_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalEntriesServiceReference.ReadByRecId_Result> ApprovalEntriesServiceReference.DEFT_ApprovalEntries_Port.ReadByRecIdAsync(ApprovalEntriesServiceReference.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalEntriesServiceReference.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            ApprovalEntriesServiceReference.ReadByRecId inValue = new ApprovalEntriesServiceReference.ReadByRecId();
            inValue.recId = recId;
            return ((ApprovalEntriesServiceReference.DEFT_ApprovalEntries_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalEntriesServiceReference.ReadMultiple_Result> ApprovalEntriesServiceReference.DEFT_ApprovalEntries_Port.ReadMultipleAsync(ApprovalEntriesServiceReference.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalEntriesServiceReference.ReadMultiple_Result> ReadMultipleAsync(ApprovalEntriesServiceReference.DEFT_ApprovalEntries_Filter[] filter, string bookmarkKey, int setSize)
        {
            ApprovalEntriesServiceReference.ReadMultiple inValue = new ApprovalEntriesServiceReference.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((ApprovalEntriesServiceReference.DEFT_ApprovalEntries_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalEntriesServiceReference.IsUpdated_Result> ApprovalEntriesServiceReference.DEFT_ApprovalEntries_Port.IsUpdatedAsync(ApprovalEntriesServiceReference.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalEntriesServiceReference.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            ApprovalEntriesServiceReference.IsUpdated inValue = new ApprovalEntriesServiceReference.IsUpdated();
            inValue.Key = Key;
            return ((ApprovalEntriesServiceReference.DEFT_ApprovalEntries_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalEntriesServiceReference.GetRecIdFromKey_Result> ApprovalEntriesServiceReference.DEFT_ApprovalEntries_Port.GetRecIdFromKeyAsync(ApprovalEntriesServiceReference.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalEntriesServiceReference.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            ApprovalEntriesServiceReference.GetRecIdFromKey inValue = new ApprovalEntriesServiceReference.GetRecIdFromKey();
            inValue.Key = Key;
            return ((ApprovalEntriesServiceReference.DEFT_ApprovalEntries_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DEFT_ApprovalEntries_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DEFT_ApprovalEntries_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://sportal-bc.defttech.co.ke:7047/BC180/WS/JSPS/Page/DEFT_ApprovalEntries");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DEFT_ApprovalEntries_PortClient.GetBindingForEndpoint(EndpointConfiguration.DEFT_ApprovalEntries_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DEFT_ApprovalEntries_PortClient.GetEndpointAddress(EndpointConfiguration.DEFT_ApprovalEntries_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            DEFT_ApprovalEntries_Port,
        }
    }
}
