//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeftSoap_LeaveRelievers
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", ConfigurationName="DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port")]
    public interface DEFT_LeaveRelievers_Port
    {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_leaverelievers:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeftSoap_LeaveRelievers.Read_Result Read(DeftSoap_LeaveRelievers.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_leaverelievers:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.Read_Result> ReadAsync(DeftSoap_LeaveRelievers.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_leaverelievers:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeftSoap_LeaveRelievers.ReadByRecId_Result ReadByRecId(DeftSoap_LeaveRelievers.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_leaverelievers:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.ReadByRecId_Result> ReadByRecIdAsync(DeftSoap_LeaveRelievers.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_leaverelievers:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeftSoap_LeaveRelievers.ReadMultiple_Result ReadMultiple(DeftSoap_LeaveRelievers.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_leaverelievers:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.ReadMultiple_Result> ReadMultipleAsync(DeftSoap_LeaveRelievers.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_leaverelievers:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeftSoap_LeaveRelievers.IsUpdated_Result IsUpdated(DeftSoap_LeaveRelievers.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_leaverelievers:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.IsUpdated_Result> IsUpdatedAsync(DeftSoap_LeaveRelievers.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_leaverelievers:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeftSoap_LeaveRelievers.GetRecIdFromKey_Result GetRecIdFromKey(DeftSoap_LeaveRelievers.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_leaverelievers:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(DeftSoap_LeaveRelievers.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_leaverelievers:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeftSoap_LeaveRelievers.Create_Result Create(DeftSoap_LeaveRelievers.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_leaverelievers:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.Create_Result> CreateAsync(DeftSoap_LeaveRelievers.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_leaverelievers:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeftSoap_LeaveRelievers.CreateMultiple_Result CreateMultiple(DeftSoap_LeaveRelievers.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_leaverelievers:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.CreateMultiple_Result> CreateMultipleAsync(DeftSoap_LeaveRelievers.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_leaverelievers:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeftSoap_LeaveRelievers.Update_Result Update(DeftSoap_LeaveRelievers.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_leaverelievers:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.Update_Result> UpdateAsync(DeftSoap_LeaveRelievers.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_leaverelievers:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeftSoap_LeaveRelievers.UpdateMultiple_Result UpdateMultiple(DeftSoap_LeaveRelievers.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_leaverelievers:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.UpdateMultiple_Result> UpdateMultipleAsync(DeftSoap_LeaveRelievers.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Result) of message Delete_Result does not match the default value (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_leaverelievers:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeftSoap_LeaveRelievers.Delete_Result Delete(DeftSoap_LeaveRelievers.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_leaverelievers:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.Delete_Result> DeleteAsync(DeftSoap_LeaveRelievers.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers")]
    public partial class DEFT_LeaveRelievers
    {
        
        private string keyField;
        
        private string staff_NoField;
        
        private string staff_NameField;
        
        private string leave_CodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Staff_No
        {
            get
            {
                return this.staff_NoField;
            }
            set
            {
                this.staff_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Staff_Name
        {
            get
            {
                return this.staff_NameField;
            }
            set
            {
                this.staff_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Leave_Code
        {
            get
            {
                return this.leave_CodeField;
            }
            set
            {
                this.leave_CodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers")]
    public partial class DEFT_LeaveRelievers_Filter
    {
        
        private DEFT_LeaveRelievers_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DEFT_LeaveRelievers_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers")]
    public enum DEFT_LeaveRelievers_Fields
    {
        
        /// <remarks/>
        Staff_No,
        
        /// <remarks/>
        Staff_Name,
        
        /// <remarks/>
        Leave_Code,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=0)]
        public string Leave_Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=1)]
        public string Staff_No;
        
        public Read()
        {
        }
        
        public Read(string Leave_Code, string Staff_No)
        {
            this.Leave_Code = Leave_Code;
            this.Staff_No = Staff_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=0)]
        public DeftSoap_LeaveRelievers.DEFT_LeaveRelievers DEFT_LeaveRelievers;
        
        public Read_Result()
        {
        }
        
        public Read_Result(DeftSoap_LeaveRelievers.DEFT_LeaveRelievers DEFT_LeaveRelievers)
        {
            this.DEFT_LeaveRelievers = DEFT_LeaveRelievers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=0)]
        public DeftSoap_LeaveRelievers.DEFT_LeaveRelievers DEFT_LeaveRelievers;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(DeftSoap_LeaveRelievers.DEFT_LeaveRelievers DEFT_LeaveRelievers)
        {
            this.DEFT_LeaveRelievers = DEFT_LeaveRelievers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DeftSoap_LeaveRelievers.DEFT_LeaveRelievers[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(DeftSoap_LeaveRelievers.DEFT_LeaveRelievers[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=0)]
        public DeftSoap_LeaveRelievers.DEFT_LeaveRelievers DEFT_LeaveRelievers;
        
        public Create()
        {
        }
        
        public Create(DeftSoap_LeaveRelievers.DEFT_LeaveRelievers DEFT_LeaveRelievers)
        {
            this.DEFT_LeaveRelievers = DEFT_LeaveRelievers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=0)]
        public DeftSoap_LeaveRelievers.DEFT_LeaveRelievers DEFT_LeaveRelievers;
        
        public Create_Result()
        {
        }
        
        public Create_Result(DeftSoap_LeaveRelievers.DEFT_LeaveRelievers DEFT_LeaveRelievers)
        {
            this.DEFT_LeaveRelievers = DEFT_LeaveRelievers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DeftSoap_LeaveRelievers.DEFT_LeaveRelievers[] DEFT_LeaveRelievers_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(DeftSoap_LeaveRelievers.DEFT_LeaveRelievers[] DEFT_LeaveRelievers_List)
        {
            this.DEFT_LeaveRelievers_List = DEFT_LeaveRelievers_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DeftSoap_LeaveRelievers.DEFT_LeaveRelievers[] DEFT_LeaveRelievers_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(DeftSoap_LeaveRelievers.DEFT_LeaveRelievers[] DEFT_LeaveRelievers_List)
        {
            this.DEFT_LeaveRelievers_List = DEFT_LeaveRelievers_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=0)]
        public DeftSoap_LeaveRelievers.DEFT_LeaveRelievers DEFT_LeaveRelievers;
        
        public Update()
        {
        }
        
        public Update(DeftSoap_LeaveRelievers.DEFT_LeaveRelievers DEFT_LeaveRelievers)
        {
            this.DEFT_LeaveRelievers = DEFT_LeaveRelievers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=0)]
        public DeftSoap_LeaveRelievers.DEFT_LeaveRelievers DEFT_LeaveRelievers;
        
        public Update_Result()
        {
        }
        
        public Update_Result(DeftSoap_LeaveRelievers.DEFT_LeaveRelievers DEFT_LeaveRelievers)
        {
            this.DEFT_LeaveRelievers = DEFT_LeaveRelievers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DeftSoap_LeaveRelievers.DEFT_LeaveRelievers[] DEFT_LeaveRelievers_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(DeftSoap_LeaveRelievers.DEFT_LeaveRelievers[] DEFT_LeaveRelievers_List)
        {
            this.DEFT_LeaveRelievers_List = DEFT_LeaveRelievers_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DeftSoap_LeaveRelievers.DEFT_LeaveRelievers[] DEFT_LeaveRelievers_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(DeftSoap_LeaveRelievers.DEFT_LeaveRelievers[] DEFT_LeaveRelievers_List)
        {
            this.DEFT_LeaveRelievers_List = DEFT_LeaveRelievers_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", IsWrapped=true)]
    public partial class Delete
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=0)]
        public string Key;
        
        public Delete()
        {
        }
        
        public Delete(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", IsWrapped=true)]
    public partial class Delete_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/deft_leaverelievers", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result()
        {
        }
        
        public Delete_Result(bool Delete_Result1)
        {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface DEFT_LeaveRelievers_PortChannel : DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class DEFT_LeaveRelievers_PortClient : System.ServiceModel.ClientBase<DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port>, DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DEFT_LeaveRelievers_PortClient() : 
                base(DEFT_LeaveRelievers_PortClient.GetDefaultBinding(), DEFT_LeaveRelievers_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DEFT_LeaveRelievers_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DEFT_LeaveRelievers_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(DEFT_LeaveRelievers_PortClient.GetBindingForEndpoint(endpointConfiguration), DEFT_LeaveRelievers_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DEFT_LeaveRelievers_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DEFT_LeaveRelievers_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DEFT_LeaveRelievers_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DEFT_LeaveRelievers_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DEFT_LeaveRelievers_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeftSoap_LeaveRelievers.Read_Result DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port.Read(DeftSoap_LeaveRelievers.Read request)
        {
            return base.Channel.Read(request);
        }
        
        public DeftSoap_LeaveRelievers.DEFT_LeaveRelievers Read(string Leave_Code, string Staff_No)
        {
            DeftSoap_LeaveRelievers.Read inValue = new DeftSoap_LeaveRelievers.Read();
            inValue.Leave_Code = Leave_Code;
            inValue.Staff_No = Staff_No;
            DeftSoap_LeaveRelievers.Read_Result retVal = ((DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port)(this)).Read(inValue);
            return retVal.DEFT_LeaveRelievers;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.Read_Result> DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port.ReadAsync(DeftSoap_LeaveRelievers.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.Read_Result> ReadAsync(string Leave_Code, string Staff_No)
        {
            DeftSoap_LeaveRelievers.Read inValue = new DeftSoap_LeaveRelievers.Read();
            inValue.Leave_Code = Leave_Code;
            inValue.Staff_No = Staff_No;
            return ((DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeftSoap_LeaveRelievers.ReadByRecId_Result DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port.ReadByRecId(DeftSoap_LeaveRelievers.ReadByRecId request)
        {
            return base.Channel.ReadByRecId(request);
        }
        
        public DeftSoap_LeaveRelievers.DEFT_LeaveRelievers ReadByRecId(string recId)
        {
            DeftSoap_LeaveRelievers.ReadByRecId inValue = new DeftSoap_LeaveRelievers.ReadByRecId();
            inValue.recId = recId;
            DeftSoap_LeaveRelievers.ReadByRecId_Result retVal = ((DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port)(this)).ReadByRecId(inValue);
            return retVal.DEFT_LeaveRelievers;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.ReadByRecId_Result> DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port.ReadByRecIdAsync(DeftSoap_LeaveRelievers.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            DeftSoap_LeaveRelievers.ReadByRecId inValue = new DeftSoap_LeaveRelievers.ReadByRecId();
            inValue.recId = recId;
            return ((DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeftSoap_LeaveRelievers.ReadMultiple_Result DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port.ReadMultiple(DeftSoap_LeaveRelievers.ReadMultiple request)
        {
            return base.Channel.ReadMultiple(request);
        }
        
        public DeftSoap_LeaveRelievers.DEFT_LeaveRelievers[] ReadMultiple(DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Filter[] filter, string bookmarkKey, int setSize)
        {
            DeftSoap_LeaveRelievers.ReadMultiple inValue = new DeftSoap_LeaveRelievers.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            DeftSoap_LeaveRelievers.ReadMultiple_Result retVal = ((DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.ReadMultiple_Result> DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port.ReadMultipleAsync(DeftSoap_LeaveRelievers.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.ReadMultiple_Result> ReadMultipleAsync(DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Filter[] filter, string bookmarkKey, int setSize)
        {
            DeftSoap_LeaveRelievers.ReadMultiple inValue = new DeftSoap_LeaveRelievers.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeftSoap_LeaveRelievers.IsUpdated_Result DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port.IsUpdated(DeftSoap_LeaveRelievers.IsUpdated request)
        {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key)
        {
            DeftSoap_LeaveRelievers.IsUpdated inValue = new DeftSoap_LeaveRelievers.IsUpdated();
            inValue.Key = Key;
            DeftSoap_LeaveRelievers.IsUpdated_Result retVal = ((DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.IsUpdated_Result> DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port.IsUpdatedAsync(DeftSoap_LeaveRelievers.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            DeftSoap_LeaveRelievers.IsUpdated inValue = new DeftSoap_LeaveRelievers.IsUpdated();
            inValue.Key = Key;
            return ((DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeftSoap_LeaveRelievers.GetRecIdFromKey_Result DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port.GetRecIdFromKey(DeftSoap_LeaveRelievers.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key)
        {
            DeftSoap_LeaveRelievers.GetRecIdFromKey inValue = new DeftSoap_LeaveRelievers.GetRecIdFromKey();
            inValue.Key = Key;
            DeftSoap_LeaveRelievers.GetRecIdFromKey_Result retVal = ((DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.GetRecIdFromKey_Result> DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port.GetRecIdFromKeyAsync(DeftSoap_LeaveRelievers.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            DeftSoap_LeaveRelievers.GetRecIdFromKey inValue = new DeftSoap_LeaveRelievers.GetRecIdFromKey();
            inValue.Key = Key;
            return ((DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeftSoap_LeaveRelievers.Create_Result DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port.Create(DeftSoap_LeaveRelievers.Create request)
        {
            return base.Channel.Create(request);
        }
        
        public void Create(ref DeftSoap_LeaveRelievers.DEFT_LeaveRelievers DEFT_LeaveRelievers)
        {
            DeftSoap_LeaveRelievers.Create inValue = new DeftSoap_LeaveRelievers.Create();
            inValue.DEFT_LeaveRelievers = DEFT_LeaveRelievers;
            DeftSoap_LeaveRelievers.Create_Result retVal = ((DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port)(this)).Create(inValue);
            DEFT_LeaveRelievers = retVal.DEFT_LeaveRelievers;
        }
        
        public System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.Create_Result> CreateAsync(DeftSoap_LeaveRelievers.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeftSoap_LeaveRelievers.CreateMultiple_Result DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port.CreateMultiple(DeftSoap_LeaveRelievers.CreateMultiple request)
        {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref DeftSoap_LeaveRelievers.DEFT_LeaveRelievers[] DEFT_LeaveRelievers_List)
        {
            DeftSoap_LeaveRelievers.CreateMultiple inValue = new DeftSoap_LeaveRelievers.CreateMultiple();
            inValue.DEFT_LeaveRelievers_List = DEFT_LeaveRelievers_List;
            DeftSoap_LeaveRelievers.CreateMultiple_Result retVal = ((DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port)(this)).CreateMultiple(inValue);
            DEFT_LeaveRelievers_List = retVal.DEFT_LeaveRelievers_List;
        }
        
        public System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.CreateMultiple_Result> CreateMultipleAsync(DeftSoap_LeaveRelievers.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeftSoap_LeaveRelievers.Update_Result DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port.Update(DeftSoap_LeaveRelievers.Update request)
        {
            return base.Channel.Update(request);
        }
        
        public void Update(ref DeftSoap_LeaveRelievers.DEFT_LeaveRelievers DEFT_LeaveRelievers)
        {
            DeftSoap_LeaveRelievers.Update inValue = new DeftSoap_LeaveRelievers.Update();
            inValue.DEFT_LeaveRelievers = DEFT_LeaveRelievers;
            DeftSoap_LeaveRelievers.Update_Result retVal = ((DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port)(this)).Update(inValue);
            DEFT_LeaveRelievers = retVal.DEFT_LeaveRelievers;
        }
        
        public System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.Update_Result> UpdateAsync(DeftSoap_LeaveRelievers.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeftSoap_LeaveRelievers.UpdateMultiple_Result DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port.UpdateMultiple(DeftSoap_LeaveRelievers.UpdateMultiple request)
        {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref DeftSoap_LeaveRelievers.DEFT_LeaveRelievers[] DEFT_LeaveRelievers_List)
        {
            DeftSoap_LeaveRelievers.UpdateMultiple inValue = new DeftSoap_LeaveRelievers.UpdateMultiple();
            inValue.DEFT_LeaveRelievers_List = DEFT_LeaveRelievers_List;
            DeftSoap_LeaveRelievers.UpdateMultiple_Result retVal = ((DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port)(this)).UpdateMultiple(inValue);
            DEFT_LeaveRelievers_List = retVal.DEFT_LeaveRelievers_List;
        }
        
        public System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.UpdateMultiple_Result> UpdateMultipleAsync(DeftSoap_LeaveRelievers.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeftSoap_LeaveRelievers.Delete_Result DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port.Delete(DeftSoap_LeaveRelievers.Delete request)
        {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key)
        {
            DeftSoap_LeaveRelievers.Delete inValue = new DeftSoap_LeaveRelievers.Delete();
            inValue.Key = Key;
            DeftSoap_LeaveRelievers.Delete_Result retVal = ((DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.Delete_Result> DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port.DeleteAsync(DeftSoap_LeaveRelievers.Delete request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeftSoap_LeaveRelievers.Delete_Result> DeleteAsync(string Key)
        {
            DeftSoap_LeaveRelievers.Delete inValue = new DeftSoap_LeaveRelievers.Delete();
            inValue.Key = Key;
            return ((DeftSoap_LeaveRelievers.DEFT_LeaveRelievers_Port)(this)).DeleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DEFT_LeaveRelievers_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DEFT_LeaveRelievers_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://amivastpc:7047/BC180/WS/JSPS/Page/DEFT_LeaveRelievers");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DEFT_LeaveRelievers_PortClient.GetBindingForEndpoint(EndpointConfiguration.DEFT_LeaveRelievers_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DEFT_LeaveRelievers_PortClient.GetEndpointAddress(EndpointConfiguration.DEFT_LeaveRelievers_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            DEFT_LeaveRelievers_Port,
        }
    }
}
