//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppraiseeAppraisalCommentsServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", ConfigurationName="AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments_Port")]
    public interface AppraiseeAppraisalComments_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.Read_Result> ReadAsync(AppraiseeAppraisalCommentsServiceReference.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.ReadByRecId_Result> ReadByRecIdAsync(AppraiseeAppraisalCommentsServiceReference.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.ReadMultiple_Result> ReadMultipleAsync(AppraiseeAppraisalCommentsServiceReference.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.IsUpdated_Result> IsUpdatedAsync(AppraiseeAppraisalCommentsServiceReference.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(AppraiseeAppraisalCommentsServiceReference.GetRecIdFromKey request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.Create_Result> CreateAsync(AppraiseeAppraisalCommentsServiceReference.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.CreateMultiple_Result> CreateMultipleAsync(AppraiseeAppraisalCommentsServiceReference.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.Update_Result> UpdateAsync(AppraiseeAppraisalCommentsServiceReference.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.UpdateMultiple_Result> UpdateMultipleAsync(AppraiseeAppraisalCommentsServiceReference.UpdateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.Delete_Result> DeleteAsync(AppraiseeAppraisalCommentsServiceReference.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments")]
    public partial class AppraiseeAppraisalComments
    {
        
        private string keyField;
        
        private bool performance_Related_DicussionsField;
        
        private bool performance_Related_DicussionsFieldSpecified;
        
        private Extent_of_Discussion_Help extent_of_Discussion_HelpField;
        
        private bool extent_of_Discussion_HelpFieldSpecified;
        
        private string comments_on_PerformanceField;
        
        private string comments_On_SupervisorField;
        
        private string appraisal_NoField;
        
        private Person personField;
        
        private bool personFieldSpecified;
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Performance_Related_Dicussions
        {
            get
            {
                return this.performance_Related_DicussionsField;
            }
            set
            {
                this.performance_Related_DicussionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Performance_Related_DicussionsSpecified
        {
            get
            {
                return this.performance_Related_DicussionsFieldSpecified;
            }
            set
            {
                this.performance_Related_DicussionsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Extent_of_Discussion_Help Extent_of_Discussion_Help
        {
            get
            {
                return this.extent_of_Discussion_HelpField;
            }
            set
            {
                this.extent_of_Discussion_HelpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Extent_of_Discussion_HelpSpecified
        {
            get
            {
                return this.extent_of_Discussion_HelpFieldSpecified;
            }
            set
            {
                this.extent_of_Discussion_HelpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Comments_on_Performance
        {
            get
            {
                return this.comments_on_PerformanceField;
            }
            set
            {
                this.comments_on_PerformanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Comments_On_Supervisor
        {
            get
            {
                return this.comments_On_SupervisorField;
            }
            set
            {
                this.comments_On_SupervisorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Appraisal_No
        {
            get
            {
                return this.appraisal_NoField;
            }
            set
            {
                this.appraisal_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Person Person
        {
            get
            {
                return this.personField;
            }
            set
            {
                this.personField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonSpecified
        {
            get
            {
                return this.personFieldSpecified;
            }
            set
            {
                this.personFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=7)]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified
        {
            get
            {
                return this.dateFieldSpecified;
            }
            set
            {
                this.dateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments")]
    public enum Extent_of_Discussion_Help
    {
        
        /// <remarks/>
        Very_Much,
        
        /// <remarks/>
        Much,
        
        /// <remarks/>
        Not_at_all,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments")]
    public enum Person
    {
        
        /// <remarks/>
        PAppraiser,
        
        /// <remarks/>
        PAppraisee,
        
        /// <remarks/>
        Second_Supervisor,
        
        /// <remarks/>
        PSecond_Supervisor,
        
        /// <remarks/>
        HR,
        
        /// <remarks/>
        PHR,
        
        /// <remarks/>
        Trust_Secretary,
        
        /// <remarks/>
        Dev_Action,
        
        /// <remarks/>
        Significant_Positive_Issues,
        
        /// <remarks/>
        Significant_Negative_Issues,
        
        /// <remarks/>
        Substantial_Achievements,
        
        /// <remarks/>
        Perfomance_Improvement_Plan,
        
        /// <remarks/>
        Staff_Training_and_Dev_Needs,
        
        /// <remarks/>
        Other_interventions,
        
        /// <remarks/>
        CEO,
        
        /// <remarks/>
        PCEO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments")]
    public partial class AppraiseeAppraisalComments_Filter
    {
        
        private AppraiseeAppraisalComments_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AppraiseeAppraisalComments_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments")]
    public enum AppraiseeAppraisalComments_Fields
    {
        
        /// <remarks/>
        Performance_Related_Dicussions,
        
        /// <remarks/>
        Extent_of_Discussion_Help,
        
        /// <remarks/>
        Comments_on_Performance,
        
        /// <remarks/>
        Comments_On_Supervisor,
        
        /// <remarks/>
        Appraisal_No,
        
        /// <remarks/>
        Person,
        
        /// <remarks/>
        Date,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=0)]
        public string Appraisal_No;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=1)]
        public string Person;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=2)]
        public string Comments_on_Performance;
        
        public Read()
        {
        }
        
        public Read(string Appraisal_No, string Person, string Comments_on_Performance)
        {
            this.Appraisal_No = Appraisal_No;
            this.Person = Person;
            this.Comments_on_Performance = Comments_on_Performance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=0)]
        public AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments AppraiseeAppraisalComments;
        
        public Read_Result()
        {
        }
        
        public Read_Result(AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments AppraiseeAppraisalComments)
        {
            this.AppraiseeAppraisalComments = AppraiseeAppraisalComments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=0)]
        public AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments AppraiseeAppraisalComments;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments AppraiseeAppraisalComments)
        {
            this.AppraiseeAppraisalComments = AppraiseeAppraisalComments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=0)]
        public AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments AppraiseeAppraisalComments;
        
        public Create()
        {
        }
        
        public Create(AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments AppraiseeAppraisalComments)
        {
            this.AppraiseeAppraisalComments = AppraiseeAppraisalComments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=0)]
        public AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments AppraiseeAppraisalComments;
        
        public Create_Result()
        {
        }
        
        public Create_Result(AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments AppraiseeAppraisalComments)
        {
            this.AppraiseeAppraisalComments = AppraiseeAppraisalComments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments[] AppraiseeAppraisalComments_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments[] AppraiseeAppraisalComments_List)
        {
            this.AppraiseeAppraisalComments_List = AppraiseeAppraisalComments_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments[] AppraiseeAppraisalComments_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments[] AppraiseeAppraisalComments_List)
        {
            this.AppraiseeAppraisalComments_List = AppraiseeAppraisalComments_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=0)]
        public AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments AppraiseeAppraisalComments;
        
        public Update()
        {
        }
        
        public Update(AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments AppraiseeAppraisalComments)
        {
            this.AppraiseeAppraisalComments = AppraiseeAppraisalComments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=0)]
        public AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments AppraiseeAppraisalComments;
        
        public Update_Result()
        {
        }
        
        public Update_Result(AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments AppraiseeAppraisalComments)
        {
            this.AppraiseeAppraisalComments = AppraiseeAppraisalComments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments[] AppraiseeAppraisalComments_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments[] AppraiseeAppraisalComments_List)
        {
            this.AppraiseeAppraisalComments_List = AppraiseeAppraisalComments_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments[] AppraiseeAppraisalComments_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments[] AppraiseeAppraisalComments_List)
        {
            this.AppraiseeAppraisalComments_List = AppraiseeAppraisalComments_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", IsWrapped=true)]
    public partial class Delete
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=0)]
        public string Key;
        
        public Delete()
        {
        }
        
        public Delete(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", IsWrapped=true)]
    public partial class Delete_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/appraiseeappraisalcomments", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result()
        {
        }
        
        public Delete_Result(bool Delete_Result1)
        {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface AppraiseeAppraisalComments_PortChannel : AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class AppraiseeAppraisalComments_PortClient : System.ServiceModel.ClientBase<AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments_Port>, AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AppraiseeAppraisalComments_PortClient() : 
                base(AppraiseeAppraisalComments_PortClient.GetDefaultBinding(), AppraiseeAppraisalComments_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AppraiseeAppraisalComments_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppraiseeAppraisalComments_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(AppraiseeAppraisalComments_PortClient.GetBindingForEndpoint(endpointConfiguration), AppraiseeAppraisalComments_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppraiseeAppraisalComments_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AppraiseeAppraisalComments_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppraiseeAppraisalComments_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AppraiseeAppraisalComments_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppraiseeAppraisalComments_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.Read_Result> AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments_Port.ReadAsync(AppraiseeAppraisalCommentsServiceReference.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.Read_Result> ReadAsync(string Appraisal_No, string Person, string Comments_on_Performance)
        {
            AppraiseeAppraisalCommentsServiceReference.Read inValue = new AppraiseeAppraisalCommentsServiceReference.Read();
            inValue.Appraisal_No = Appraisal_No;
            inValue.Person = Person;
            inValue.Comments_on_Performance = Comments_on_Performance;
            return ((AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.ReadByRecId_Result> AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments_Port.ReadByRecIdAsync(AppraiseeAppraisalCommentsServiceReference.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            AppraiseeAppraisalCommentsServiceReference.ReadByRecId inValue = new AppraiseeAppraisalCommentsServiceReference.ReadByRecId();
            inValue.recId = recId;
            return ((AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.ReadMultiple_Result> AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments_Port.ReadMultipleAsync(AppraiseeAppraisalCommentsServiceReference.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.ReadMultiple_Result> ReadMultipleAsync(AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments_Filter[] filter, string bookmarkKey, int setSize)
        {
            AppraiseeAppraisalCommentsServiceReference.ReadMultiple inValue = new AppraiseeAppraisalCommentsServiceReference.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.IsUpdated_Result> AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments_Port.IsUpdatedAsync(AppraiseeAppraisalCommentsServiceReference.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            AppraiseeAppraisalCommentsServiceReference.IsUpdated inValue = new AppraiseeAppraisalCommentsServiceReference.IsUpdated();
            inValue.Key = Key;
            return ((AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.GetRecIdFromKey_Result> AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments_Port.GetRecIdFromKeyAsync(AppraiseeAppraisalCommentsServiceReference.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            AppraiseeAppraisalCommentsServiceReference.GetRecIdFromKey inValue = new AppraiseeAppraisalCommentsServiceReference.GetRecIdFromKey();
            inValue.Key = Key;
            return ((AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.Create_Result> CreateAsync(AppraiseeAppraisalCommentsServiceReference.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.CreateMultiple_Result> CreateMultipleAsync(AppraiseeAppraisalCommentsServiceReference.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.Update_Result> UpdateAsync(AppraiseeAppraisalCommentsServiceReference.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.UpdateMultiple_Result> UpdateMultipleAsync(AppraiseeAppraisalCommentsServiceReference.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.Delete_Result> AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments_Port.DeleteAsync(AppraiseeAppraisalCommentsServiceReference.Delete request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppraiseeAppraisalCommentsServiceReference.Delete_Result> DeleteAsync(string Key)
        {
            AppraiseeAppraisalCommentsServiceReference.Delete inValue = new AppraiseeAppraisalCommentsServiceReference.Delete();
            inValue.Key = Key;
            return ((AppraiseeAppraisalCommentsServiceReference.AppraiseeAppraisalComments_Port)(this)).DeleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AppraiseeAppraisalComments_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AppraiseeAppraisalComments_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://sportal-bc.defttech.co.ke:7047/BC180/WS/JSPS/Page/AppraiseeAppraisalComme" +
                        "nts");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AppraiseeAppraisalComments_PortClient.GetBindingForEndpoint(EndpointConfiguration.AppraiseeAppraisalComments_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AppraiseeAppraisalComments_PortClient.GetEndpointAddress(EndpointConfiguration.AppraiseeAppraisalComments_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            AppraiseeAppraisalComments_Port,
        }
    }
}
