//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitSubjectServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", ConfigurationName="UnitSubjectServiceReference.unitsubject_Port")]
    public interface unitsubject_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/unitsubject:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UnitSubjectServiceReference.Read_Result> ReadAsync(UnitSubjectServiceReference.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/unitsubject:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UnitSubjectServiceReference.ReadByRecId_Result> ReadByRecIdAsync(UnitSubjectServiceReference.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/unitsubject:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UnitSubjectServiceReference.ReadMultiple_Result> ReadMultipleAsync(UnitSubjectServiceReference.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/unitsubject:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UnitSubjectServiceReference.IsUpdated_Result> IsUpdatedAsync(UnitSubjectServiceReference.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/unitsubject:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UnitSubjectServiceReference.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(UnitSubjectServiceReference.GetRecIdFromKey request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/unitsubject:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UnitSubjectServiceReference.Create_Result> CreateAsync(UnitSubjectServiceReference.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/unitsubject:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UnitSubjectServiceReference.CreateMultiple_Result> CreateMultipleAsync(UnitSubjectServiceReference.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/unitsubject:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UnitSubjectServiceReference.Update_Result> UpdateAsync(UnitSubjectServiceReference.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/unitsubject:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UnitSubjectServiceReference.UpdateMultiple_Result> UpdateMultipleAsync(UnitSubjectServiceReference.UpdateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/unitsubject:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UnitSubjectServiceReference.Delete_Result> DeleteAsync(UnitSubjectServiceReference.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject")]
    public partial class unitsubject
    {
        
        private string keyField;
        
        private string codeField;
        
        private string programme_CodeField;
        
        private string moduleField;
        
        private string year_CodeField;
        
        private string termField;
        
        private string descriptionField;
        
        private int normal_SlotsField;
        
        private bool normal_SlotsFieldSpecified;
        
        private Unit_Type unit_TypeField;
        
        private bool unit_TypeFieldSpecified;
        
        private decimal no_UnitsField;
        
        private bool no_UnitsFieldSpecified;
        
        private decimal certificate_AmountField;
        
        private bool certificate_AmountFieldSpecified;
        
        private decimal diploma_AmountField;
        
        private bool diploma_AmountFieldSpecified;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private bool time_TableField;
        
        private bool time_TableFieldSpecified;
        
        private bool not_AllocatedField;
        
        private bool not_AllocatedFieldSpecified;
        
        private string student_TypeField;
        
        private string unit_ClassField;
        
        private decimal unit_Class_SizeField;
        
        private bool unit_Class_SizeFieldSpecified;
        
        private bool common_UnitField;
        
        private bool common_UnitFieldSpecified;
        
        private bool attachmentField;
        
        private bool attachmentFieldSpecified;
        
        private decimal credit_HoursField;
        
        private bool credit_HoursFieldSpecified;
        
        private string g_L_AccountField;
        
        private string term_FilterField;
        
        private int students_RegisteredField;
        
        private bool students_RegisteredFieldSpecified;
        
        private decimal total_IncomeField;
        
        private bool total_IncomeFieldSpecified;
        
        private string remarksField;
        
        private string prerequisite_ModuleField;
        
        private string prerequisite_TermField;
        
        private string prerequisiteField;
        
        private string departmentField;
        
        private bool archivedField;
        
        private bool archivedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Programme_Code
        {
            get
            {
                return this.programme_CodeField;
            }
            set
            {
                this.programme_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Module
        {
            get
            {
                return this.moduleField;
            }
            set
            {
                this.moduleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Year_Code
        {
            get
            {
                return this.year_CodeField;
            }
            set
            {
                this.year_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Term
        {
            get
            {
                return this.termField;
            }
            set
            {
                this.termField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Normal_Slots
        {
            get
            {
                return this.normal_SlotsField;
            }
            set
            {
                this.normal_SlotsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Normal_SlotsSpecified
        {
            get
            {
                return this.normal_SlotsFieldSpecified;
            }
            set
            {
                this.normal_SlotsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Unit_Type Unit_Type
        {
            get
            {
                return this.unit_TypeField;
            }
            set
            {
                this.unit_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unit_TypeSpecified
        {
            get
            {
                return this.unit_TypeFieldSpecified;
            }
            set
            {
                this.unit_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal No_Units
        {
            get
            {
                return this.no_UnitsField;
            }
            set
            {
                this.no_UnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool No_UnitsSpecified
        {
            get
            {
                return this.no_UnitsFieldSpecified;
            }
            set
            {
                this.no_UnitsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal Certificate_Amount
        {
            get
            {
                return this.certificate_AmountField;
            }
            set
            {
                this.certificate_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Certificate_AmountSpecified
        {
            get
            {
                return this.certificate_AmountFieldSpecified;
            }
            set
            {
                this.certificate_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal Diploma_Amount
        {
            get
            {
                return this.diploma_AmountField;
            }
            set
            {
                this.diploma_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Diploma_AmountSpecified
        {
            get
            {
                return this.diploma_AmountFieldSpecified;
            }
            set
            {
                this.diploma_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified
        {
            get
            {
                return this.amountFieldSpecified;
            }
            set
            {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool Time_Table
        {
            get
            {
                return this.time_TableField;
            }
            set
            {
                this.time_TableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Time_TableSpecified
        {
            get
            {
                return this.time_TableFieldSpecified;
            }
            set
            {
                this.time_TableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool Not_Allocated
        {
            get
            {
                return this.not_AllocatedField;
            }
            set
            {
                this.not_AllocatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Not_AllocatedSpecified
        {
            get
            {
                return this.not_AllocatedFieldSpecified;
            }
            set
            {
                this.not_AllocatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Student_Type
        {
            get
            {
                return this.student_TypeField;
            }
            set
            {
                this.student_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Unit_Class
        {
            get
            {
                return this.unit_ClassField;
            }
            set
            {
                this.unit_ClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public decimal Unit_Class_Size
        {
            get
            {
                return this.unit_Class_SizeField;
            }
            set
            {
                this.unit_Class_SizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unit_Class_SizeSpecified
        {
            get
            {
                return this.unit_Class_SizeFieldSpecified;
            }
            set
            {
                this.unit_Class_SizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool Common_Unit
        {
            get
            {
                return this.common_UnitField;
            }
            set
            {
                this.common_UnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Common_UnitSpecified
        {
            get
            {
                return this.common_UnitFieldSpecified;
            }
            set
            {
                this.common_UnitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public bool Attachment
        {
            get
            {
                return this.attachmentField;
            }
            set
            {
                this.attachmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AttachmentSpecified
        {
            get
            {
                return this.attachmentFieldSpecified;
            }
            set
            {
                this.attachmentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public decimal Credit_Hours
        {
            get
            {
                return this.credit_HoursField;
            }
            set
            {
                this.credit_HoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Credit_HoursSpecified
        {
            get
            {
                return this.credit_HoursFieldSpecified;
            }
            set
            {
                this.credit_HoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string G_L_Account
        {
            get
            {
                return this.g_L_AccountField;
            }
            set
            {
                this.g_L_AccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Term_Filter
        {
            get
            {
                return this.term_FilterField;
            }
            set
            {
                this.term_FilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int Students_Registered
        {
            get
            {
                return this.students_RegisteredField;
            }
            set
            {
                this.students_RegisteredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Students_RegisteredSpecified
        {
            get
            {
                return this.students_RegisteredFieldSpecified;
            }
            set
            {
                this.students_RegisteredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public decimal Total_Income
        {
            get
            {
                return this.total_IncomeField;
            }
            set
            {
                this.total_IncomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Total_IncomeSpecified
        {
            get
            {
                return this.total_IncomeFieldSpecified;
            }
            set
            {
                this.total_IncomeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Prerequisite_Module
        {
            get
            {
                return this.prerequisite_ModuleField;
            }
            set
            {
                this.prerequisite_ModuleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Prerequisite_Term
        {
            get
            {
                return this.prerequisite_TermField;
            }
            set
            {
                this.prerequisite_TermField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Prerequisite
        {
            get
            {
                return this.prerequisiteField;
            }
            set
            {
                this.prerequisiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string Department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public bool Archived
        {
            get
            {
                return this.archivedField;
            }
            set
            {
                this.archivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArchivedSpecified
        {
            get
            {
                return this.archivedFieldSpecified;
            }
            set
            {
                this.archivedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject")]
    public enum Unit_Type
    {
        
        /// <remarks/>
        Core,
        
        /// <remarks/>
        Elective,
        
        /// <remarks/>
        Required,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject")]
    public partial class unitsubject_Filter
    {
        
        private unitsubject_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public unitsubject_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject")]
    public enum unitsubject_Fields
    {
        
        /// <remarks/>
        Code,
        
        /// <remarks/>
        Programme_Code,
        
        /// <remarks/>
        Module,
        
        /// <remarks/>
        Year_Code,
        
        /// <remarks/>
        Term,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Normal_Slots,
        
        /// <remarks/>
        Unit_Type,
        
        /// <remarks/>
        No_Units,
        
        /// <remarks/>
        Certificate_Amount,
        
        /// <remarks/>
        Diploma_Amount,
        
        /// <remarks/>
        Amount,
        
        /// <remarks/>
        Time_Table,
        
        /// <remarks/>
        Not_Allocated,
        
        /// <remarks/>
        Student_Type,
        
        /// <remarks/>
        Unit_Class,
        
        /// <remarks/>
        Unit_Class_Size,
        
        /// <remarks/>
        Common_Unit,
        
        /// <remarks/>
        Attachment,
        
        /// <remarks/>
        Credit_Hours,
        
        /// <remarks/>
        G_L_Account,
        
        /// <remarks/>
        Term_Filter,
        
        /// <remarks/>
        Students_Registered,
        
        /// <remarks/>
        Total_Income,
        
        /// <remarks/>
        Remarks,
        
        /// <remarks/>
        Prerequisite_Module,
        
        /// <remarks/>
        Prerequisite_Term,
        
        /// <remarks/>
        Prerequisite,
        
        /// <remarks/>
        Department,
        
        /// <remarks/>
        Archived,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/unitsubject", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=0)]
        public string Programme_Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=1)]
        public string Year_Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=2)]
        public string Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=3)]
        public string Term;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=4)]
        public string Module;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=5)]
        public string Student_Type;
        
        public Read()
        {
        }
        
        public Read(string Programme_Code, string Year_Code, string Code, string Term, string Module, string Student_Type)
        {
            this.Programme_Code = Programme_Code;
            this.Year_Code = Year_Code;
            this.Code = Code;
            this.Term = Term;
            this.Module = Module;
            this.Student_Type = Student_Type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/unitsubject", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=0)]
        public UnitSubjectServiceReference.unitsubject unitsubject;
        
        public Read_Result()
        {
        }
        
        public Read_Result(UnitSubjectServiceReference.unitsubject unitsubject)
        {
            this.unitsubject = unitsubject;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/unitsubject", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/unitsubject", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=0)]
        public UnitSubjectServiceReference.unitsubject unitsubject;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(UnitSubjectServiceReference.unitsubject unitsubject)
        {
            this.unitsubject = unitsubject;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/unitsubject", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public UnitSubjectServiceReference.unitsubject_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(UnitSubjectServiceReference.unitsubject_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/unitsubject", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public UnitSubjectServiceReference.unitsubject[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(UnitSubjectServiceReference.unitsubject[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/unitsubject", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/unitsubject", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/unitsubject", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/unitsubject", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/unitsubject", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=0)]
        public UnitSubjectServiceReference.unitsubject unitsubject;
        
        public Create()
        {
        }
        
        public Create(UnitSubjectServiceReference.unitsubject unitsubject)
        {
            this.unitsubject = unitsubject;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/unitsubject", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=0)]
        public UnitSubjectServiceReference.unitsubject unitsubject;
        
        public Create_Result()
        {
        }
        
        public Create_Result(UnitSubjectServiceReference.unitsubject unitsubject)
        {
            this.unitsubject = unitsubject;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/unitsubject", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public UnitSubjectServiceReference.unitsubject[] unitsubject_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(UnitSubjectServiceReference.unitsubject[] unitsubject_List)
        {
            this.unitsubject_List = unitsubject_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/unitsubject", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public UnitSubjectServiceReference.unitsubject[] unitsubject_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(UnitSubjectServiceReference.unitsubject[] unitsubject_List)
        {
            this.unitsubject_List = unitsubject_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/unitsubject", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=0)]
        public UnitSubjectServiceReference.unitsubject unitsubject;
        
        public Update()
        {
        }
        
        public Update(UnitSubjectServiceReference.unitsubject unitsubject)
        {
            this.unitsubject = unitsubject;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/unitsubject", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=0)]
        public UnitSubjectServiceReference.unitsubject unitsubject;
        
        public Update_Result()
        {
        }
        
        public Update_Result(UnitSubjectServiceReference.unitsubject unitsubject)
        {
            this.unitsubject = unitsubject;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/unitsubject", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public UnitSubjectServiceReference.unitsubject[] unitsubject_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(UnitSubjectServiceReference.unitsubject[] unitsubject_List)
        {
            this.unitsubject_List = unitsubject_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/unitsubject", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public UnitSubjectServiceReference.unitsubject[] unitsubject_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(UnitSubjectServiceReference.unitsubject[] unitsubject_List)
        {
            this.unitsubject_List = unitsubject_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/unitsubject", IsWrapped=true)]
    public partial class Delete
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=0)]
        public string Key;
        
        public Delete()
        {
        }
        
        public Delete(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/unitsubject", IsWrapped=true)]
    public partial class Delete_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/unitsubject", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result()
        {
        }
        
        public Delete_Result(bool Delete_Result1)
        {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface unitsubject_PortChannel : UnitSubjectServiceReference.unitsubject_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class unitsubject_PortClient : System.ServiceModel.ClientBase<UnitSubjectServiceReference.unitsubject_Port>, UnitSubjectServiceReference.unitsubject_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public unitsubject_PortClient() : 
                base(unitsubject_PortClient.GetDefaultBinding(), unitsubject_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.unitsubject_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public unitsubject_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(unitsubject_PortClient.GetBindingForEndpoint(endpointConfiguration), unitsubject_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public unitsubject_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(unitsubject_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public unitsubject_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(unitsubject_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public unitsubject_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitSubjectServiceReference.Read_Result> UnitSubjectServiceReference.unitsubject_Port.ReadAsync(UnitSubjectServiceReference.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitSubjectServiceReference.Read_Result> ReadAsync(string Programme_Code, string Year_Code, string Code, string Term, string Module, string Student_Type)
        {
            UnitSubjectServiceReference.Read inValue = new UnitSubjectServiceReference.Read();
            inValue.Programme_Code = Programme_Code;
            inValue.Year_Code = Year_Code;
            inValue.Code = Code;
            inValue.Term = Term;
            inValue.Module = Module;
            inValue.Student_Type = Student_Type;
            return ((UnitSubjectServiceReference.unitsubject_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitSubjectServiceReference.ReadByRecId_Result> UnitSubjectServiceReference.unitsubject_Port.ReadByRecIdAsync(UnitSubjectServiceReference.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitSubjectServiceReference.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            UnitSubjectServiceReference.ReadByRecId inValue = new UnitSubjectServiceReference.ReadByRecId();
            inValue.recId = recId;
            return ((UnitSubjectServiceReference.unitsubject_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitSubjectServiceReference.ReadMultiple_Result> UnitSubjectServiceReference.unitsubject_Port.ReadMultipleAsync(UnitSubjectServiceReference.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitSubjectServiceReference.ReadMultiple_Result> ReadMultipleAsync(UnitSubjectServiceReference.unitsubject_Filter[] filter, string bookmarkKey, int setSize)
        {
            UnitSubjectServiceReference.ReadMultiple inValue = new UnitSubjectServiceReference.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((UnitSubjectServiceReference.unitsubject_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitSubjectServiceReference.IsUpdated_Result> UnitSubjectServiceReference.unitsubject_Port.IsUpdatedAsync(UnitSubjectServiceReference.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitSubjectServiceReference.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            UnitSubjectServiceReference.IsUpdated inValue = new UnitSubjectServiceReference.IsUpdated();
            inValue.Key = Key;
            return ((UnitSubjectServiceReference.unitsubject_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitSubjectServiceReference.GetRecIdFromKey_Result> UnitSubjectServiceReference.unitsubject_Port.GetRecIdFromKeyAsync(UnitSubjectServiceReference.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitSubjectServiceReference.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            UnitSubjectServiceReference.GetRecIdFromKey inValue = new UnitSubjectServiceReference.GetRecIdFromKey();
            inValue.Key = Key;
            return ((UnitSubjectServiceReference.unitsubject_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<UnitSubjectServiceReference.Create_Result> CreateAsync(UnitSubjectServiceReference.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitSubjectServiceReference.CreateMultiple_Result> CreateMultipleAsync(UnitSubjectServiceReference.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitSubjectServiceReference.Update_Result> UpdateAsync(UnitSubjectServiceReference.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitSubjectServiceReference.UpdateMultiple_Result> UpdateMultipleAsync(UnitSubjectServiceReference.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitSubjectServiceReference.Delete_Result> UnitSubjectServiceReference.unitsubject_Port.DeleteAsync(UnitSubjectServiceReference.Delete request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitSubjectServiceReference.Delete_Result> DeleteAsync(string Key)
        {
            UnitSubjectServiceReference.Delete inValue = new UnitSubjectServiceReference.Delete();
            inValue.Key = Key;
            return ((UnitSubjectServiceReference.unitsubject_Port)(this)).DeleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.unitsubject_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.unitsubject_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://sportal-bc.defttech.co.ke:7047/BC180/WS/JSPS/Page/unitsubject");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return unitsubject_PortClient.GetBindingForEndpoint(EndpointConfiguration.unitsubject_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return unitsubject_PortClient.GetEndpointAddress(EndpointConfiguration.unitsubject_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            unitsubject_Port,
        }
    }
}
