//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeftSoap_EmpApplicationCard
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", ConfigurationName="DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port")]
    public interface DEFT_EmployeeLeaveApplicationCard_Port
    {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeftSoap_EmpApplicationCard.Read_Result Read(DeftSoap_EmpApplicationCard.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.Read_Result> ReadAsync(DeftSoap_EmpApplicationCard.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard:ReadByRecId" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeftSoap_EmpApplicationCard.ReadByRecId_Result ReadByRecId(DeftSoap_EmpApplicationCard.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard:ReadByRecId" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.ReadByRecId_Result> ReadByRecIdAsync(DeftSoap_EmpApplicationCard.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard:ReadMultipl" +
            "e", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeftSoap_EmpApplicationCard.ReadMultiple_Result ReadMultiple(DeftSoap_EmpApplicationCard.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard:ReadMultipl" +
            "e", ReplyAction="*")]
        System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.ReadMultiple_Result> ReadMultipleAsync(DeftSoap_EmpApplicationCard.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeftSoap_EmpApplicationCard.IsUpdated_Result IsUpdated(DeftSoap_EmpApplicationCard.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.IsUpdated_Result> IsUpdatedAsync(DeftSoap_EmpApplicationCard.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard:GetRecIdFro" +
            "mKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeftSoap_EmpApplicationCard.GetRecIdFromKey_Result GetRecIdFromKey(DeftSoap_EmpApplicationCard.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard:GetRecIdFro" +
            "mKey", ReplyAction="*")]
        System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(DeftSoap_EmpApplicationCard.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeftSoap_EmpApplicationCard.Create_Result Create(DeftSoap_EmpApplicationCard.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.Create_Result> CreateAsync(DeftSoap_EmpApplicationCard.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard:CreateMulti" +
            "ple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeftSoap_EmpApplicationCard.CreateMultiple_Result CreateMultiple(DeftSoap_EmpApplicationCard.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard:CreateMulti" +
            "ple", ReplyAction="*")]
        System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.CreateMultiple_Result> CreateMultipleAsync(DeftSoap_EmpApplicationCard.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeftSoap_EmpApplicationCard.Update_Result Update(DeftSoap_EmpApplicationCard.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.Update_Result> UpdateAsync(DeftSoap_EmpApplicationCard.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard:UpdateMulti" +
            "ple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeftSoap_EmpApplicationCard.UpdateMultiple_Result UpdateMultiple(DeftSoap_EmpApplicationCard.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard:UpdateMulti" +
            "ple", ReplyAction="*")]
        System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.UpdateMultiple_Result> UpdateMultipleAsync(DeftSoap_EmpApplicationCard.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Control47_Result) of message Delete_Control47_Result does not match the default value (Delete_Control47)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard:Delete_Cont" +
            "rol47", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeftSoap_EmpApplicationCard.Delete_Control47_Result Delete_Control47(DeftSoap_EmpApplicationCard.Delete_Control47 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard:Delete_Cont" +
            "rol47", ReplyAction="*")]
        System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.Delete_Control47_Result> Delete_Control47Async(DeftSoap_EmpApplicationCard.Delete_Control47 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard")]
    public partial class DEFT_EmployeeLeaveApplicationCard
    {
        
        private string keyField;
        
        private string application_NoField;
        
        private System.DateTime application_DateField;
        
        private bool application_DateFieldSpecified;
        
        private bool apply_on_behalfField;
        
        private bool apply_on_behalfFieldSpecified;
        
        private string employee_NoField;
        
        private string employee_NameField;
        
        private Employment_Type employment_TypeField;
        
        private bool employment_TypeFieldSpecified;
        
        private string responsibility_CenterField;
        
        private string mobile_NoField;
        
        private string user_IDField;
        
        private string shortcut_Dimension_1_CodeField;
        
        private string shortcut_Dimension_2_CodeField;
        
        private string leave_PeriodField;
        
        private string leave_CodeField;
        
        private Leave_Status leave_StatusField;
        
        private bool leave_StatusFieldSpecified;
        
        private Status statusField;
        
        private bool statusFieldSpecified;
        
        private decimal leave_EntitlmentField;
        
        private bool leave_EntitlmentFieldSpecified;
        
        private decimal balance_brought_forwardField;
        
        private bool balance_brought_forwardFieldSpecified;
        
        private decimal leave_Earned_to_DateField;
        
        private bool leave_Earned_to_DateFieldSpecified;
        
        private decimal leaveAdjustmentsField;
        
        private bool leaveAdjustmentsFieldSpecified;
        
        private decimal total_Leave_Days_TakenField;
        
        private bool total_Leave_Days_TakenFieldSpecified;
        
        private decimal recalled_DaysField;
        
        private bool recalled_DaysFieldSpecified;
        
        private decimal days_AbsentField;
        
        private bool days_AbsentFieldSpecified;
        
        private decimal off_DaysField;
        
        private bool off_DaysFieldSpecified;
        
        private decimal leave_balanceField;
        
        private bool leave_balanceFieldSpecified;
        
        private System.DateTime planner_Start_DateField;
        
        private bool planner_Start_DateFieldSpecified;
        
        private bool return_same_dayField;
        
        private bool return_same_dayFieldSpecified;
        
        private decimal days_AppliedField;
        
        private bool days_AppliedFieldSpecified;
        
        private System.DateTime start_DateField;
        
        private bool start_DateFieldSpecified;
        
        private System.DateTime end_DateField;
        
        private bool end_DateFieldSpecified;
        
        private System.DateTime resumption_DateField;
        
        private bool resumption_DateFieldSpecified;
        
        private decimal annual_Leave_Entitlement_BalField;
        
        private bool annual_Leave_Entitlement_BalFieldSpecified;
        
        private string duties_Taken_Over_ByField;
        
        private string relieving_NameField;
        
        private bool leave_Allowance_PayableField;
        
        private bool leave_Allowance_PayableFieldSpecified;
        
        private int no_of_ApprovalsField;
        
        private bool no_of_ApprovalsFieldSpecified;
        
        private Leave_Relievers[] control47Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Application_No
        {
            get
            {
                return this.application_NoField;
            }
            set
            {
                this.application_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime Application_Date
        {
            get
            {
                return this.application_DateField;
            }
            set
            {
                this.application_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Application_DateSpecified
        {
            get
            {
                return this.application_DateFieldSpecified;
            }
            set
            {
                this.application_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool Apply_on_behalf
        {
            get
            {
                return this.apply_on_behalfField;
            }
            set
            {
                this.apply_on_behalfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Apply_on_behalfSpecified
        {
            get
            {
                return this.apply_on_behalfFieldSpecified;
            }
            set
            {
                this.apply_on_behalfFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Employee_No
        {
            get
            {
                return this.employee_NoField;
            }
            set
            {
                this.employee_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Employee_Name
        {
            get
            {
                return this.employee_NameField;
            }
            set
            {
                this.employee_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Employment_Type Employment_Type
        {
            get
            {
                return this.employment_TypeField;
            }
            set
            {
                this.employment_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Employment_TypeSpecified
        {
            get
            {
                return this.employment_TypeFieldSpecified;
            }
            set
            {
                this.employment_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Responsibility_Center
        {
            get
            {
                return this.responsibility_CenterField;
            }
            set
            {
                this.responsibility_CenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Mobile_No
        {
            get
            {
                return this.mobile_NoField;
            }
            set
            {
                this.mobile_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string User_ID
        {
            get
            {
                return this.user_IDField;
            }
            set
            {
                this.user_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Shortcut_Dimension_1_Code
        {
            get
            {
                return this.shortcut_Dimension_1_CodeField;
            }
            set
            {
                this.shortcut_Dimension_1_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Shortcut_Dimension_2_Code
        {
            get
            {
                return this.shortcut_Dimension_2_CodeField;
            }
            set
            {
                this.shortcut_Dimension_2_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Leave_Period
        {
            get
            {
                return this.leave_PeriodField;
            }
            set
            {
                this.leave_PeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Leave_Code
        {
            get
            {
                return this.leave_CodeField;
            }
            set
            {
                this.leave_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public Leave_Status Leave_Status
        {
            get
            {
                return this.leave_StatusField;
            }
            set
            {
                this.leave_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Leave_StatusSpecified
        {
            get
            {
                return this.leave_StatusFieldSpecified;
            }
            set
            {
                this.leave_StatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public decimal Leave_Entitlment
        {
            get
            {
                return this.leave_EntitlmentField;
            }
            set
            {
                this.leave_EntitlmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Leave_EntitlmentSpecified
        {
            get
            {
                return this.leave_EntitlmentFieldSpecified;
            }
            set
            {
                this.leave_EntitlmentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public decimal Balance_brought_forward
        {
            get
            {
                return this.balance_brought_forwardField;
            }
            set
            {
                this.balance_brought_forwardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Balance_brought_forwardSpecified
        {
            get
            {
                return this.balance_brought_forwardFieldSpecified;
            }
            set
            {
                this.balance_brought_forwardFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public decimal Leave_Earned_to_Date
        {
            get
            {
                return this.leave_Earned_to_DateField;
            }
            set
            {
                this.leave_Earned_to_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Leave_Earned_to_DateSpecified
        {
            get
            {
                return this.leave_Earned_to_DateFieldSpecified;
            }
            set
            {
                this.leave_Earned_to_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public decimal LeaveAdjustments
        {
            get
            {
                return this.leaveAdjustmentsField;
            }
            set
            {
                this.leaveAdjustmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LeaveAdjustmentsSpecified
        {
            get
            {
                return this.leaveAdjustmentsFieldSpecified;
            }
            set
            {
                this.leaveAdjustmentsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public decimal Total_Leave_Days_Taken
        {
            get
            {
                return this.total_Leave_Days_TakenField;
            }
            set
            {
                this.total_Leave_Days_TakenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Total_Leave_Days_TakenSpecified
        {
            get
            {
                return this.total_Leave_Days_TakenFieldSpecified;
            }
            set
            {
                this.total_Leave_Days_TakenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public decimal Recalled_Days
        {
            get
            {
                return this.recalled_DaysField;
            }
            set
            {
                this.recalled_DaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Recalled_DaysSpecified
        {
            get
            {
                return this.recalled_DaysFieldSpecified;
            }
            set
            {
                this.recalled_DaysFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public decimal Days_Absent
        {
            get
            {
                return this.days_AbsentField;
            }
            set
            {
                this.days_AbsentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Days_AbsentSpecified
        {
            get
            {
                return this.days_AbsentFieldSpecified;
            }
            set
            {
                this.days_AbsentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public decimal Off_Days
        {
            get
            {
                return this.off_DaysField;
            }
            set
            {
                this.off_DaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Off_DaysSpecified
        {
            get
            {
                return this.off_DaysFieldSpecified;
            }
            set
            {
                this.off_DaysFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public decimal Leave_balance
        {
            get
            {
                return this.leave_balanceField;
            }
            set
            {
                this.leave_balanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Leave_balanceSpecified
        {
            get
            {
                return this.leave_balanceFieldSpecified;
            }
            set
            {
                this.leave_balanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=25)]
        public System.DateTime Planner_Start_Date
        {
            get
            {
                return this.planner_Start_DateField;
            }
            set
            {
                this.planner_Start_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Planner_Start_DateSpecified
        {
            get
            {
                return this.planner_Start_DateFieldSpecified;
            }
            set
            {
                this.planner_Start_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public bool Return_same_day
        {
            get
            {
                return this.return_same_dayField;
            }
            set
            {
                this.return_same_dayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Return_same_daySpecified
        {
            get
            {
                return this.return_same_dayFieldSpecified;
            }
            set
            {
                this.return_same_dayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public decimal Days_Applied
        {
            get
            {
                return this.days_AppliedField;
            }
            set
            {
                this.days_AppliedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Days_AppliedSpecified
        {
            get
            {
                return this.days_AppliedFieldSpecified;
            }
            set
            {
                this.days_AppliedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=28)]
        public System.DateTime Start_Date
        {
            get
            {
                return this.start_DateField;
            }
            set
            {
                this.start_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Start_DateSpecified
        {
            get
            {
                return this.start_DateFieldSpecified;
            }
            set
            {
                this.start_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=29)]
        public System.DateTime End_Date
        {
            get
            {
                return this.end_DateField;
            }
            set
            {
                this.end_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool End_DateSpecified
        {
            get
            {
                return this.end_DateFieldSpecified;
            }
            set
            {
                this.end_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=30)]
        public System.DateTime Resumption_Date
        {
            get
            {
                return this.resumption_DateField;
            }
            set
            {
                this.resumption_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Resumption_DateSpecified
        {
            get
            {
                return this.resumption_DateFieldSpecified;
            }
            set
            {
                this.resumption_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public decimal Annual_Leave_Entitlement_Bal
        {
            get
            {
                return this.annual_Leave_Entitlement_BalField;
            }
            set
            {
                this.annual_Leave_Entitlement_BalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Annual_Leave_Entitlement_BalSpecified
        {
            get
            {
                return this.annual_Leave_Entitlement_BalFieldSpecified;
            }
            set
            {
                this.annual_Leave_Entitlement_BalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string Duties_Taken_Over_By
        {
            get
            {
                return this.duties_Taken_Over_ByField;
            }
            set
            {
                this.duties_Taken_Over_ByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string Relieving_Name
        {
            get
            {
                return this.relieving_NameField;
            }
            set
            {
                this.relieving_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public bool Leave_Allowance_Payable
        {
            get
            {
                return this.leave_Allowance_PayableField;
            }
            set
            {
                this.leave_Allowance_PayableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Leave_Allowance_PayableSpecified
        {
            get
            {
                return this.leave_Allowance_PayableFieldSpecified;
            }
            set
            {
                this.leave_Allowance_PayableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public int No_of_Approvals
        {
            get
            {
                return this.no_of_ApprovalsField;
            }
            set
            {
                this.no_of_ApprovalsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool No_of_ApprovalsSpecified
        {
            get
            {
                return this.no_of_ApprovalsFieldSpecified;
            }
            set
            {
                this.no_of_ApprovalsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=36)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Leave_Relievers[] Control47
        {
            get
            {
                return this.control47Field;
            }
            set
            {
                this.control47Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard")]
    public enum Employment_Type
    {
        
        /// <remarks/>
        Contract,
        
        /// <remarks/>
        Permanent,
        
        /// <remarks/>
        Trustee,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard")]
    public enum Leave_Status
    {
        
        /// <remarks/>
        Being_Processed,
        
        /// <remarks/>
        Approved,
        
        /// <remarks/>
        Rejected,
        
        /// <remarks/>
        Canceled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard")]
    public enum Status
    {
        
        /// <remarks/>
        Open,
        
        /// <remarks/>
        Released,
        
        /// <remarks/>
        Pending_Approval,
        
        /// <remarks/>
        Pending_Prepayment,
        
        /// <remarks/>
        Rejected,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard")]
    public partial class Leave_Relievers
    {
        
        private string keyField;
        
        private string staff_NoField;
        
        private string staff_NameField;
        
        private string leave_CodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Staff_No
        {
            get
            {
                return this.staff_NoField;
            }
            set
            {
                this.staff_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Staff_Name
        {
            get
            {
                return this.staff_NameField;
            }
            set
            {
                this.staff_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Leave_Code
        {
            get
            {
                return this.leave_CodeField;
            }
            set
            {
                this.leave_CodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard")]
    public partial class DEFT_EmployeeLeaveApplicationCard_Filter
    {
        
        private DEFT_EmployeeLeaveApplicationCard_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DEFT_EmployeeLeaveApplicationCard_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard")]
    public enum DEFT_EmployeeLeaveApplicationCard_Fields
    {
        
        /// <remarks/>
        Application_No,
        
        /// <remarks/>
        Application_Date,
        
        /// <remarks/>
        Apply_on_behalf,
        
        /// <remarks/>
        Employee_No,
        
        /// <remarks/>
        Employee_Name,
        
        /// <remarks/>
        Employment_Type,
        
        /// <remarks/>
        Responsibility_Center,
        
        /// <remarks/>
        Mobile_No,
        
        /// <remarks/>
        User_ID,
        
        /// <remarks/>
        Shortcut_Dimension_1_Code,
        
        /// <remarks/>
        Shortcut_Dimension_2_Code,
        
        /// <remarks/>
        Leave_Period,
        
        /// <remarks/>
        Leave_Code,
        
        /// <remarks/>
        Leave_Status,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        Leave_Entitlment,
        
        /// <remarks/>
        Balance_brought_forward,
        
        /// <remarks/>
        Leave_Earned_to_Date,
        
        /// <remarks/>
        LeaveAdjustments,
        
        /// <remarks/>
        Total_Leave_Days_Taken,
        
        /// <remarks/>
        Recalled_Days,
        
        /// <remarks/>
        Days_Absent,
        
        /// <remarks/>
        Off_Days,
        
        /// <remarks/>
        Leave_balance,
        
        /// <remarks/>
        Planner_Start_Date,
        
        /// <remarks/>
        Return_same_day,
        
        /// <remarks/>
        Days_Applied,
        
        /// <remarks/>
        Start_Date,
        
        /// <remarks/>
        End_Date,
        
        /// <remarks/>
        Resumption_Date,
        
        /// <remarks/>
        Annual_Leave_Entitlement_Bal,
        
        /// <remarks/>
        Duties_Taken_Over_By,
        
        /// <remarks/>
        Relieving_Name,
        
        /// <remarks/>
        Leave_Allowance_Payable,
        
        /// <remarks/>
        No_of_Approvals,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=0)]
        public string Application_No;
        
        public Read()
        {
        }
        
        public Read(string Application_No)
        {
            this.Application_No = Application_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=0)]
        public DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard DEFT_EmployeeLeaveApplicationCard;
        
        public Read_Result()
        {
        }
        
        public Read_Result(DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard DEFT_EmployeeLeaveApplicationCard)
        {
            this.DEFT_EmployeeLeaveApplicationCard = DEFT_EmployeeLeaveApplicationCard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=0)]
        public DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard DEFT_EmployeeLeaveApplicationCard;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard DEFT_EmployeeLeaveApplicationCard)
        {
            this.DEFT_EmployeeLeaveApplicationCard = DEFT_EmployeeLeaveApplicationCard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=0)]
        public DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard DEFT_EmployeeLeaveApplicationCard;
        
        public Create()
        {
        }
        
        public Create(DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard DEFT_EmployeeLeaveApplicationCard)
        {
            this.DEFT_EmployeeLeaveApplicationCard = DEFT_EmployeeLeaveApplicationCard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=0)]
        public DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard DEFT_EmployeeLeaveApplicationCard;
        
        public Create_Result()
        {
        }
        
        public Create_Result(DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard DEFT_EmployeeLeaveApplicationCard)
        {
            this.DEFT_EmployeeLeaveApplicationCard = DEFT_EmployeeLeaveApplicationCard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard[] DEFT_EmployeeLeaveApplicationCard_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard[] DEFT_EmployeeLeaveApplicationCard_List)
        {
            this.DEFT_EmployeeLeaveApplicationCard_List = DEFT_EmployeeLeaveApplicationCard_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard[] DEFT_EmployeeLeaveApplicationCard_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard[] DEFT_EmployeeLeaveApplicationCard_List)
        {
            this.DEFT_EmployeeLeaveApplicationCard_List = DEFT_EmployeeLeaveApplicationCard_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=0)]
        public DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard DEFT_EmployeeLeaveApplicationCard;
        
        public Update()
        {
        }
        
        public Update(DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard DEFT_EmployeeLeaveApplicationCard)
        {
            this.DEFT_EmployeeLeaveApplicationCard = DEFT_EmployeeLeaveApplicationCard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=0)]
        public DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard DEFT_EmployeeLeaveApplicationCard;
        
        public Update_Result()
        {
        }
        
        public Update_Result(DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard DEFT_EmployeeLeaveApplicationCard)
        {
            this.DEFT_EmployeeLeaveApplicationCard = DEFT_EmployeeLeaveApplicationCard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard[] DEFT_EmployeeLeaveApplicationCard_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard[] DEFT_EmployeeLeaveApplicationCard_List)
        {
            this.DEFT_EmployeeLeaveApplicationCard_List = DEFT_EmployeeLeaveApplicationCard_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard[] DEFT_EmployeeLeaveApplicationCard_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard[] DEFT_EmployeeLeaveApplicationCard_List)
        {
            this.DEFT_EmployeeLeaveApplicationCard_List = DEFT_EmployeeLeaveApplicationCard_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Control47", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", IsWrapped=true)]
    public partial class Delete_Control47
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=0)]
        public string Control47_Key;
        
        public Delete_Control47()
        {
        }
        
        public Delete_Control47(string Control47_Key)
        {
            this.Control47_Key = Control47_Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Control47_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", IsWrapped=true)]
    public partial class Delete_Control47_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Control47_Result", Namespace="urn:microsoft-dynamics-schemas/page/deft_employeeleaveapplicationcard", Order=0)]
        public bool Delete_Control47_Result1;
        
        public Delete_Control47_Result()
        {
        }
        
        public Delete_Control47_Result(bool Delete_Control47_Result1)
        {
            this.Delete_Control47_Result1 = Delete_Control47_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface DEFT_EmployeeLeaveApplicationCard_PortChannel : DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class DEFT_EmployeeLeaveApplicationCard_PortClient : System.ServiceModel.ClientBase<DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port>, DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DEFT_EmployeeLeaveApplicationCard_PortClient() : 
                base(DEFT_EmployeeLeaveApplicationCard_PortClient.GetDefaultBinding(), DEFT_EmployeeLeaveApplicationCard_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DEFT_EmployeeLeaveApplicationCard_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DEFT_EmployeeLeaveApplicationCard_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(DEFT_EmployeeLeaveApplicationCard_PortClient.GetBindingForEndpoint(endpointConfiguration), DEFT_EmployeeLeaveApplicationCard_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DEFT_EmployeeLeaveApplicationCard_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DEFT_EmployeeLeaveApplicationCard_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DEFT_EmployeeLeaveApplicationCard_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DEFT_EmployeeLeaveApplicationCard_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DEFT_EmployeeLeaveApplicationCard_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeftSoap_EmpApplicationCard.Read_Result DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port.Read(DeftSoap_EmpApplicationCard.Read request)
        {
            return base.Channel.Read(request);
        }
        
        public DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard Read(string Application_No)
        {
            DeftSoap_EmpApplicationCard.Read inValue = new DeftSoap_EmpApplicationCard.Read();
            inValue.Application_No = Application_No;
            DeftSoap_EmpApplicationCard.Read_Result retVal = ((DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port)(this)).Read(inValue);
            return retVal.DEFT_EmployeeLeaveApplicationCard;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.Read_Result> DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port.ReadAsync(DeftSoap_EmpApplicationCard.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.Read_Result> ReadAsync(string Application_No)
        {
            DeftSoap_EmpApplicationCard.Read inValue = new DeftSoap_EmpApplicationCard.Read();
            inValue.Application_No = Application_No;
            return ((DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeftSoap_EmpApplicationCard.ReadByRecId_Result DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port.ReadByRecId(DeftSoap_EmpApplicationCard.ReadByRecId request)
        {
            return base.Channel.ReadByRecId(request);
        }
        
        public DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard ReadByRecId(string recId)
        {
            DeftSoap_EmpApplicationCard.ReadByRecId inValue = new DeftSoap_EmpApplicationCard.ReadByRecId();
            inValue.recId = recId;
            DeftSoap_EmpApplicationCard.ReadByRecId_Result retVal = ((DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port)(this)).ReadByRecId(inValue);
            return retVal.DEFT_EmployeeLeaveApplicationCard;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.ReadByRecId_Result> DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port.ReadByRecIdAsync(DeftSoap_EmpApplicationCard.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            DeftSoap_EmpApplicationCard.ReadByRecId inValue = new DeftSoap_EmpApplicationCard.ReadByRecId();
            inValue.recId = recId;
            return ((DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeftSoap_EmpApplicationCard.ReadMultiple_Result DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port.ReadMultiple(DeftSoap_EmpApplicationCard.ReadMultiple request)
        {
            return base.Channel.ReadMultiple(request);
        }
        
        public DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard[] ReadMultiple(DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Filter[] filter, string bookmarkKey, int setSize)
        {
            DeftSoap_EmpApplicationCard.ReadMultiple inValue = new DeftSoap_EmpApplicationCard.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            DeftSoap_EmpApplicationCard.ReadMultiple_Result retVal = ((DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.ReadMultiple_Result> DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port.ReadMultipleAsync(DeftSoap_EmpApplicationCard.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.ReadMultiple_Result> ReadMultipleAsync(DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Filter[] filter, string bookmarkKey, int setSize)
        {
            DeftSoap_EmpApplicationCard.ReadMultiple inValue = new DeftSoap_EmpApplicationCard.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeftSoap_EmpApplicationCard.IsUpdated_Result DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port.IsUpdated(DeftSoap_EmpApplicationCard.IsUpdated request)
        {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key)
        {
            DeftSoap_EmpApplicationCard.IsUpdated inValue = new DeftSoap_EmpApplicationCard.IsUpdated();
            inValue.Key = Key;
            DeftSoap_EmpApplicationCard.IsUpdated_Result retVal = ((DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.IsUpdated_Result> DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port.IsUpdatedAsync(DeftSoap_EmpApplicationCard.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            DeftSoap_EmpApplicationCard.IsUpdated inValue = new DeftSoap_EmpApplicationCard.IsUpdated();
            inValue.Key = Key;
            return ((DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeftSoap_EmpApplicationCard.GetRecIdFromKey_Result DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port.GetRecIdFromKey(DeftSoap_EmpApplicationCard.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key)
        {
            DeftSoap_EmpApplicationCard.GetRecIdFromKey inValue = new DeftSoap_EmpApplicationCard.GetRecIdFromKey();
            inValue.Key = Key;
            DeftSoap_EmpApplicationCard.GetRecIdFromKey_Result retVal = ((DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.GetRecIdFromKey_Result> DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port.GetRecIdFromKeyAsync(DeftSoap_EmpApplicationCard.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            DeftSoap_EmpApplicationCard.GetRecIdFromKey inValue = new DeftSoap_EmpApplicationCard.GetRecIdFromKey();
            inValue.Key = Key;
            return ((DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeftSoap_EmpApplicationCard.Create_Result DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port.Create(DeftSoap_EmpApplicationCard.Create request)
        {
            return base.Channel.Create(request);
        }
        
        public void Create(ref DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard DEFT_EmployeeLeaveApplicationCard)
        {
            DeftSoap_EmpApplicationCard.Create inValue = new DeftSoap_EmpApplicationCard.Create();
            inValue.DEFT_EmployeeLeaveApplicationCard = DEFT_EmployeeLeaveApplicationCard;
            DeftSoap_EmpApplicationCard.Create_Result retVal = ((DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port)(this)).Create(inValue);
            DEFT_EmployeeLeaveApplicationCard = retVal.DEFT_EmployeeLeaveApplicationCard;
        }
        
        public System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.Create_Result> CreateAsync(DeftSoap_EmpApplicationCard.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeftSoap_EmpApplicationCard.CreateMultiple_Result DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port.CreateMultiple(DeftSoap_EmpApplicationCard.CreateMultiple request)
        {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard[] DEFT_EmployeeLeaveApplicationCard_List)
        {
            DeftSoap_EmpApplicationCard.CreateMultiple inValue = new DeftSoap_EmpApplicationCard.CreateMultiple();
            inValue.DEFT_EmployeeLeaveApplicationCard_List = DEFT_EmployeeLeaveApplicationCard_List;
            DeftSoap_EmpApplicationCard.CreateMultiple_Result retVal = ((DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port)(this)).CreateMultiple(inValue);
            DEFT_EmployeeLeaveApplicationCard_List = retVal.DEFT_EmployeeLeaveApplicationCard_List;
        }
        
        public System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.CreateMultiple_Result> CreateMultipleAsync(DeftSoap_EmpApplicationCard.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeftSoap_EmpApplicationCard.Update_Result DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port.Update(DeftSoap_EmpApplicationCard.Update request)
        {
            return base.Channel.Update(request);
        }
        
        public void Update(ref DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard DEFT_EmployeeLeaveApplicationCard)
        {
            DeftSoap_EmpApplicationCard.Update inValue = new DeftSoap_EmpApplicationCard.Update();
            inValue.DEFT_EmployeeLeaveApplicationCard = DEFT_EmployeeLeaveApplicationCard;
            DeftSoap_EmpApplicationCard.Update_Result retVal = ((DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port)(this)).Update(inValue);
            DEFT_EmployeeLeaveApplicationCard = retVal.DEFT_EmployeeLeaveApplicationCard;
        }
        
        public System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.Update_Result> UpdateAsync(DeftSoap_EmpApplicationCard.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeftSoap_EmpApplicationCard.UpdateMultiple_Result DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port.UpdateMultiple(DeftSoap_EmpApplicationCard.UpdateMultiple request)
        {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard[] DEFT_EmployeeLeaveApplicationCard_List)
        {
            DeftSoap_EmpApplicationCard.UpdateMultiple inValue = new DeftSoap_EmpApplicationCard.UpdateMultiple();
            inValue.DEFT_EmployeeLeaveApplicationCard_List = DEFT_EmployeeLeaveApplicationCard_List;
            DeftSoap_EmpApplicationCard.UpdateMultiple_Result retVal = ((DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port)(this)).UpdateMultiple(inValue);
            DEFT_EmployeeLeaveApplicationCard_List = retVal.DEFT_EmployeeLeaveApplicationCard_List;
        }
        
        public System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.UpdateMultiple_Result> UpdateMultipleAsync(DeftSoap_EmpApplicationCard.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeftSoap_EmpApplicationCard.Delete_Control47_Result DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port.Delete_Control47(DeftSoap_EmpApplicationCard.Delete_Control47 request)
        {
            return base.Channel.Delete_Control47(request);
        }
        
        public bool Delete_Control47(string Control47_Key)
        {
            DeftSoap_EmpApplicationCard.Delete_Control47 inValue = new DeftSoap_EmpApplicationCard.Delete_Control47();
            inValue.Control47_Key = Control47_Key;
            DeftSoap_EmpApplicationCard.Delete_Control47_Result retVal = ((DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port)(this)).Delete_Control47(inValue);
            return retVal.Delete_Control47_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.Delete_Control47_Result> DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port.Delete_Control47Async(DeftSoap_EmpApplicationCard.Delete_Control47 request)
        {
            return base.Channel.Delete_Control47Async(request);
        }
        
        public System.Threading.Tasks.Task<DeftSoap_EmpApplicationCard.Delete_Control47_Result> Delete_Control47Async(string Control47_Key)
        {
            DeftSoap_EmpApplicationCard.Delete_Control47 inValue = new DeftSoap_EmpApplicationCard.Delete_Control47();
            inValue.Control47_Key = Control47_Key;
            return ((DeftSoap_EmpApplicationCard.DEFT_EmployeeLeaveApplicationCard_Port)(this)).Delete_Control47Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DEFT_EmployeeLeaveApplicationCard_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DEFT_EmployeeLeaveApplicationCard_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://amivastpc:7047/BC180/WS/JSPS/Page/DEFT_EmployeeLeaveApplicationCard");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DEFT_EmployeeLeaveApplicationCard_PortClient.GetBindingForEndpoint(EndpointConfiguration.DEFT_EmployeeLeaveApplicationCard_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DEFT_EmployeeLeaveApplicationCard_PortClient.GetEndpointAddress(EndpointConfiguration.DEFT_EmployeeLeaveApplicationCard_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            DEFT_EmployeeLeaveApplicationCard_Port,
        }
    }
}
