//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApprovalGoalsServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", ConfigurationName="ApprovalGoalsServiceReference.AppraisalGoalsEntries_Port")]
    public interface AppraisalGoalsEntries_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ApprovalGoalsServiceReference.Read_Result> ReadAsync(ApprovalGoalsServiceReference.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ApprovalGoalsServiceReference.ReadByRecId_Result> ReadByRecIdAsync(ApprovalGoalsServiceReference.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ApprovalGoalsServiceReference.ReadMultiple_Result> ReadMultipleAsync(ApprovalGoalsServiceReference.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ApprovalGoalsServiceReference.IsUpdated_Result> IsUpdatedAsync(ApprovalGoalsServiceReference.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ApprovalGoalsServiceReference.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(ApprovalGoalsServiceReference.GetRecIdFromKey request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ApprovalGoalsServiceReference.Create_Result> CreateAsync(ApprovalGoalsServiceReference.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ApprovalGoalsServiceReference.CreateMultiple_Result> CreateMultipleAsync(ApprovalGoalsServiceReference.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ApprovalGoalsServiceReference.Update_Result> UpdateAsync(ApprovalGoalsServiceReference.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ApprovalGoalsServiceReference.UpdateMultiple_Result> UpdateMultipleAsync(ApprovalGoalsServiceReference.UpdateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ApprovalGoalsServiceReference.Delete_Result> DeleteAsync(ApprovalGoalsServiceReference.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries")]
    public partial class AppraisalGoalsEntries
    {
        
        private string keyField;
        
        private int line_NoField;
        
        private bool line_NoFieldSpecified;
        
        private string objective_CodeField;
        
        private string key_ResponsibilityField;
        
        private string initiative_codeField;
        
        private string descriptionField;
        
        private string activity_codeField;
        
        private string key_IndicatorsField;
        
        private string taskField;
        
        private string kPIField;
        
        private decimal self_RatingField;
        
        private bool self_RatingFieldSpecified;
        
        private decimal ratingField;
        
        private bool ratingFieldSpecified;
        
        private decimal maximum_ScoreField;
        
        private bool maximum_ScoreFieldSpecified;
        
        private string agreed_perfomance_targetsField;
        
        private string actual_targetsField;
        
        private decimal mid_Year_AppraisalField;
        
        private bool mid_Year_AppraisalFieldSpecified;
        
        private decimal weightingField;
        
        private bool weightingFieldSpecified;
        
        private decimal varianceField;
        
        private bool varianceFieldSpecified;
        
        private string results_Achieved_CommentsField;
        
        private string appraisal_NoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Line_No
        {
            get
            {
                return this.line_NoField;
            }
            set
            {
                this.line_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Line_NoSpecified
        {
            get
            {
                return this.line_NoFieldSpecified;
            }
            set
            {
                this.line_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Objective_Code
        {
            get
            {
                return this.objective_CodeField;
            }
            set
            {
                this.objective_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Key_Responsibility
        {
            get
            {
                return this.key_ResponsibilityField;
            }
            set
            {
                this.key_ResponsibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Initiative_code
        {
            get
            {
                return this.initiative_codeField;
            }
            set
            {
                this.initiative_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Activity_code
        {
            get
            {
                return this.activity_codeField;
            }
            set
            {
                this.activity_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Key_Indicators
        {
            get
            {
                return this.key_IndicatorsField;
            }
            set
            {
                this.key_IndicatorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Task
        {
            get
            {
                return this.taskField;
            }
            set
            {
                this.taskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string KPI
        {
            get
            {
                return this.kPIField;
            }
            set
            {
                this.kPIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal Self_Rating
        {
            get
            {
                return this.self_RatingField;
            }
            set
            {
                this.self_RatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Self_RatingSpecified
        {
            get
            {
                return this.self_RatingFieldSpecified;
            }
            set
            {
                this.self_RatingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal Rating
        {
            get
            {
                return this.ratingField;
            }
            set
            {
                this.ratingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RatingSpecified
        {
            get
            {
                return this.ratingFieldSpecified;
            }
            set
            {
                this.ratingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal Maximum_Score
        {
            get
            {
                return this.maximum_ScoreField;
            }
            set
            {
                this.maximum_ScoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Maximum_ScoreSpecified
        {
            get
            {
                return this.maximum_ScoreFieldSpecified;
            }
            set
            {
                this.maximum_ScoreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Agreed_perfomance_targets
        {
            get
            {
                return this.agreed_perfomance_targetsField;
            }
            set
            {
                this.agreed_perfomance_targetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Actual_targets
        {
            get
            {
                return this.actual_targetsField;
            }
            set
            {
                this.actual_targetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public decimal Mid_Year_Appraisal
        {
            get
            {
                return this.mid_Year_AppraisalField;
            }
            set
            {
                this.mid_Year_AppraisalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Mid_Year_AppraisalSpecified
        {
            get
            {
                return this.mid_Year_AppraisalFieldSpecified;
            }
            set
            {
                this.mid_Year_AppraisalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public decimal Weighting
        {
            get
            {
                return this.weightingField;
            }
            set
            {
                this.weightingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightingSpecified
        {
            get
            {
                return this.weightingFieldSpecified;
            }
            set
            {
                this.weightingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public decimal Variance
        {
            get
            {
                return this.varianceField;
            }
            set
            {
                this.varianceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VarianceSpecified
        {
            get
            {
                return this.varianceFieldSpecified;
            }
            set
            {
                this.varianceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Results_Achieved_Comments
        {
            get
            {
                return this.results_Achieved_CommentsField;
            }
            set
            {
                this.results_Achieved_CommentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Appraisal_No
        {
            get
            {
                return this.appraisal_NoField;
            }
            set
            {
                this.appraisal_NoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries")]
    public partial class AppraisalGoalsEntries_Filter
    {
        
        private AppraisalGoalsEntries_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AppraisalGoalsEntries_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries")]
    public enum AppraisalGoalsEntries_Fields
    {
        
        /// <remarks/>
        Line_No,
        
        /// <remarks/>
        Objective_Code,
        
        /// <remarks/>
        Key_Responsibility,
        
        /// <remarks/>
        Initiative_code,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Activity_code,
        
        /// <remarks/>
        Key_Indicators,
        
        /// <remarks/>
        Task,
        
        /// <remarks/>
        KPI,
        
        /// <remarks/>
        Self_Rating,
        
        /// <remarks/>
        Rating,
        
        /// <remarks/>
        Maximum_Score,
        
        /// <remarks/>
        Agreed_perfomance_targets,
        
        /// <remarks/>
        Actual_targets,
        
        /// <remarks/>
        Mid_Year_Appraisal,
        
        /// <remarks/>
        Weighting,
        
        /// <remarks/>
        Variance,
        
        /// <remarks/>
        Results_Achieved_Comments,
        
        /// <remarks/>
        Appraisal_No,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=0)]
        public string Appraisal_No;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=1)]
        public int Line_No;
        
        public Read()
        {
        }
        
        public Read(string Appraisal_No, int Line_No)
        {
            this.Appraisal_No = Appraisal_No;
            this.Line_No = Line_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=0)]
        public ApprovalGoalsServiceReference.AppraisalGoalsEntries AppraisalGoalsEntries;
        
        public Read_Result()
        {
        }
        
        public Read_Result(ApprovalGoalsServiceReference.AppraisalGoalsEntries AppraisalGoalsEntries)
        {
            this.AppraisalGoalsEntries = AppraisalGoalsEntries;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=0)]
        public ApprovalGoalsServiceReference.AppraisalGoalsEntries AppraisalGoalsEntries;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(ApprovalGoalsServiceReference.AppraisalGoalsEntries AppraisalGoalsEntries)
        {
            this.AppraisalGoalsEntries = AppraisalGoalsEntries;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public ApprovalGoalsServiceReference.AppraisalGoalsEntries_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(ApprovalGoalsServiceReference.AppraisalGoalsEntries_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ApprovalGoalsServiceReference.AppraisalGoalsEntries[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(ApprovalGoalsServiceReference.AppraisalGoalsEntries[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=0)]
        public ApprovalGoalsServiceReference.AppraisalGoalsEntries AppraisalGoalsEntries;
        
        public Create()
        {
        }
        
        public Create(ApprovalGoalsServiceReference.AppraisalGoalsEntries AppraisalGoalsEntries)
        {
            this.AppraisalGoalsEntries = AppraisalGoalsEntries;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=0)]
        public ApprovalGoalsServiceReference.AppraisalGoalsEntries AppraisalGoalsEntries;
        
        public Create_Result()
        {
        }
        
        public Create_Result(ApprovalGoalsServiceReference.AppraisalGoalsEntries AppraisalGoalsEntries)
        {
            this.AppraisalGoalsEntries = AppraisalGoalsEntries;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ApprovalGoalsServiceReference.AppraisalGoalsEntries[] AppraisalGoalsEntries_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(ApprovalGoalsServiceReference.AppraisalGoalsEntries[] AppraisalGoalsEntries_List)
        {
            this.AppraisalGoalsEntries_List = AppraisalGoalsEntries_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ApprovalGoalsServiceReference.AppraisalGoalsEntries[] AppraisalGoalsEntries_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(ApprovalGoalsServiceReference.AppraisalGoalsEntries[] AppraisalGoalsEntries_List)
        {
            this.AppraisalGoalsEntries_List = AppraisalGoalsEntries_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=0)]
        public ApprovalGoalsServiceReference.AppraisalGoalsEntries AppraisalGoalsEntries;
        
        public Update()
        {
        }
        
        public Update(ApprovalGoalsServiceReference.AppraisalGoalsEntries AppraisalGoalsEntries)
        {
            this.AppraisalGoalsEntries = AppraisalGoalsEntries;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=0)]
        public ApprovalGoalsServiceReference.AppraisalGoalsEntries AppraisalGoalsEntries;
        
        public Update_Result()
        {
        }
        
        public Update_Result(ApprovalGoalsServiceReference.AppraisalGoalsEntries AppraisalGoalsEntries)
        {
            this.AppraisalGoalsEntries = AppraisalGoalsEntries;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ApprovalGoalsServiceReference.AppraisalGoalsEntries[] AppraisalGoalsEntries_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(ApprovalGoalsServiceReference.AppraisalGoalsEntries[] AppraisalGoalsEntries_List)
        {
            this.AppraisalGoalsEntries_List = AppraisalGoalsEntries_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ApprovalGoalsServiceReference.AppraisalGoalsEntries[] AppraisalGoalsEntries_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(ApprovalGoalsServiceReference.AppraisalGoalsEntries[] AppraisalGoalsEntries_List)
        {
            this.AppraisalGoalsEntries_List = AppraisalGoalsEntries_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", IsWrapped=true)]
    public partial class Delete
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=0)]
        public string Key;
        
        public Delete()
        {
        }
        
        public Delete(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", IsWrapped=true)]
    public partial class Delete_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/appraisalgoalsentries", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result()
        {
        }
        
        public Delete_Result(bool Delete_Result1)
        {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface AppraisalGoalsEntries_PortChannel : ApprovalGoalsServiceReference.AppraisalGoalsEntries_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class AppraisalGoalsEntries_PortClient : System.ServiceModel.ClientBase<ApprovalGoalsServiceReference.AppraisalGoalsEntries_Port>, ApprovalGoalsServiceReference.AppraisalGoalsEntries_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AppraisalGoalsEntries_PortClient() : 
                base(AppraisalGoalsEntries_PortClient.GetDefaultBinding(), AppraisalGoalsEntries_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AppraisalGoalsEntries_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppraisalGoalsEntries_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(AppraisalGoalsEntries_PortClient.GetBindingForEndpoint(endpointConfiguration), AppraisalGoalsEntries_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppraisalGoalsEntries_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AppraisalGoalsEntries_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppraisalGoalsEntries_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AppraisalGoalsEntries_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppraisalGoalsEntries_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalGoalsServiceReference.Read_Result> ApprovalGoalsServiceReference.AppraisalGoalsEntries_Port.ReadAsync(ApprovalGoalsServiceReference.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalGoalsServiceReference.Read_Result> ReadAsync(string Appraisal_No, int Line_No)
        {
            ApprovalGoalsServiceReference.Read inValue = new ApprovalGoalsServiceReference.Read();
            inValue.Appraisal_No = Appraisal_No;
            inValue.Line_No = Line_No;
            return ((ApprovalGoalsServiceReference.AppraisalGoalsEntries_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalGoalsServiceReference.ReadByRecId_Result> ApprovalGoalsServiceReference.AppraisalGoalsEntries_Port.ReadByRecIdAsync(ApprovalGoalsServiceReference.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalGoalsServiceReference.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            ApprovalGoalsServiceReference.ReadByRecId inValue = new ApprovalGoalsServiceReference.ReadByRecId();
            inValue.recId = recId;
            return ((ApprovalGoalsServiceReference.AppraisalGoalsEntries_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalGoalsServiceReference.ReadMultiple_Result> ApprovalGoalsServiceReference.AppraisalGoalsEntries_Port.ReadMultipleAsync(ApprovalGoalsServiceReference.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalGoalsServiceReference.ReadMultiple_Result> ReadMultipleAsync(ApprovalGoalsServiceReference.AppraisalGoalsEntries_Filter[] filter, string bookmarkKey, int setSize)
        {
            ApprovalGoalsServiceReference.ReadMultiple inValue = new ApprovalGoalsServiceReference.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((ApprovalGoalsServiceReference.AppraisalGoalsEntries_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalGoalsServiceReference.IsUpdated_Result> ApprovalGoalsServiceReference.AppraisalGoalsEntries_Port.IsUpdatedAsync(ApprovalGoalsServiceReference.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalGoalsServiceReference.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            ApprovalGoalsServiceReference.IsUpdated inValue = new ApprovalGoalsServiceReference.IsUpdated();
            inValue.Key = Key;
            return ((ApprovalGoalsServiceReference.AppraisalGoalsEntries_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalGoalsServiceReference.GetRecIdFromKey_Result> ApprovalGoalsServiceReference.AppraisalGoalsEntries_Port.GetRecIdFromKeyAsync(ApprovalGoalsServiceReference.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalGoalsServiceReference.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            ApprovalGoalsServiceReference.GetRecIdFromKey inValue = new ApprovalGoalsServiceReference.GetRecIdFromKey();
            inValue.Key = Key;
            return ((ApprovalGoalsServiceReference.AppraisalGoalsEntries_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ApprovalGoalsServiceReference.Create_Result> CreateAsync(ApprovalGoalsServiceReference.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalGoalsServiceReference.CreateMultiple_Result> CreateMultipleAsync(ApprovalGoalsServiceReference.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalGoalsServiceReference.Update_Result> UpdateAsync(ApprovalGoalsServiceReference.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalGoalsServiceReference.UpdateMultiple_Result> UpdateMultipleAsync(ApprovalGoalsServiceReference.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalGoalsServiceReference.Delete_Result> ApprovalGoalsServiceReference.AppraisalGoalsEntries_Port.DeleteAsync(ApprovalGoalsServiceReference.Delete request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalGoalsServiceReference.Delete_Result> DeleteAsync(string Key)
        {
            ApprovalGoalsServiceReference.Delete inValue = new ApprovalGoalsServiceReference.Delete();
            inValue.Key = Key;
            return ((ApprovalGoalsServiceReference.AppraisalGoalsEntries_Port)(this)).DeleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AppraisalGoalsEntries_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AppraisalGoalsEntries_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://sportal-bc.defttech.co.ke:7047/BC180/WS/JSPS/Page/AppraisalGoalsEntries");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AppraisalGoalsEntries_PortClient.GetBindingForEndpoint(EndpointConfiguration.AppraisalGoalsEntries_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AppraisalGoalsEntries_PortClient.GetEndpointAddress(EndpointConfiguration.AppraisalGoalsEntries_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            AppraisalGoalsEntries_Port,
        }
    }
}
